Add fastify-response-caching to ecosystem
fastify/fastify pull request #2559
Opened 2020-09-17 16:07 UTC by codeaholicguy

Hello everyone,

We are using Fastify for the microservice edge-gateway solution in ShopBack. Our system usually has a spike in traffic so we need to reduce the workload of downstream services, as well as prevent redundant operations, then we developed a plugin for caching the response and preventing the gateway to fire the same request at the spike time.

We think it is worth sharing it with the Fastify community and we can together improve this.

Thanks.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2020-09-17 16:59 UTC, mcollina requested changes
I'm adding a few things to solve before landing:

* [ ] https://github.com/codeaholicguy/fastify-response-caching/issues/1
* [ ] https://github.com/codeaholicguy/fastify-response-caching/issues/2
* [ ] https://github.com/codeaholicguy/fastify-response-caching/issues/3
* [ ] https://github.com/codeaholicguy/fastify-response-caching/issues/4

2020-09-18 09:14 UTC, codeaholicguy commented
Hi @mcollina, it's very nice when getting your feedback, those are very useful. We fixed:

[x] https://github.com/codeaholicguy/fastify-response-caching/issues/1
[x] https://github.com/codeaholicguy/fastify-response-caching/issues/2
[x] https://github.com/codeaholicguy/fastify-response-caching/issues/4

About https://github.com/codeaholicguy/fastify-response-caching/issues/3, we considered them as an improvement and will do it in the very near future.

Thanks again.

2020-09-18 13:49 UTC, RafaelGSS approved these changes
Good improvement!

LGTM

2020-09-18 14:19 UTC, mcollina approved these changes
lgtm

2020-09-18 15:36 UTC, merged