bug #2578 fix
fastify/fastify pull request #2579
Opened 2020-09-24 10:17 UTC by x0us

bug #2578 fix

2020-09-24 10:27 UTC, fox1t commented
I am confused by the types here. @mcollina could the serializers return objects with any propreties?

2020-09-24 11:34 UTC, mcollina commented
> I am confused by the types here. @mcollina could the serializers return objects with any properties?

yes

2020-09-24 12:03 UTC, fox1t commented
Then I think that these types represents only the default values that we can see here: https://github.com/fastify/fastify/blob/master/lib/logger.js#L48

I suppose that if custom types are needed for serializers, https://www.fastify.io/docs/latest/TypeScript/#example-5-specifying-logger-types should be used @x0us.

Let's wait for more info from @Ethan-Arrowood :)

2020-09-24 16:16 UTC, Ethan-Arrowood commented
These changes look good to me. +1 on expanding the docs too!

2020-09-24 21:41 UTC, mcollina commented
Can you please add a unit test?

2020-09-25 06:59 UTC, mcollina approved these changes
lgtm

2020-09-25 07:20 UTC, fox1t requested changes

2020-09-25 07:21 UTC, fox1t requested changes

2020-09-25 07:21 UTC, fox1t commented on types/logger.d.ts
>        statusCode: string | number;
```suggestion
      statusCode: string | number;
      [key: string]: unknown;
```

2020-09-25 07:21 UTC, fox1t commented
Can you please add a test case for additional properties?

2020-10-04 11:18 UTC, mcollina commented
@fox1t is this ok to land?

2020-10-06 14:08 UTC, fox1t approved these changes
LGTM

2020-10-06 14:50 UTC, merged