Add types to async fastify hooks
fastify/fastify pull request #2615
Opened 2020-10-14 00:40 UTC by RafaelGSS

I did not add types for non-documented async hooks like: `onRegister` hook. I would like to adjust it in another PR.

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2020-10-14 04:06 UTC, L2jLiga commented
Can't we use overloads?

*example*:
```typescript
/**
 * `onRequest` is the first hook to be executed in the request lifecycle. There was no previous hook, the next hook will be `preParsing`.
 *  Notice: in the `onRequest` hook, request.body will always be null, because the body parsing happens before the `preHandler` hook.
 */
export interface onRequestHookHandler<
  RawServer extends RawServerBase = RawServerDefault,
  RawRequest extends RawRequestDefaultExpression<RawServer> = RawRequestDefaultExpression<RawServer>,
  RawReply extends RawReplyDefaultExpression<RawServer> = RawReplyDefaultExpression<RawServer>,
  RouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  ContextConfig = ContextConfigDefault
> {
  (
    request: FastifyRequest<RouteGeneric, RawServer, RawRequest>,
    reply: FastifyReply<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig>,
    done: HookHandlerDoneFunction
  ): void;

  (
    request: FastifyRequest<RouteGeneric, RawServer, RawRequest>,
    reply: FastifyReply<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig>,
  ): Promise<unknown>;
}
```

2020-10-14 10:10 UTC, zekth commented
@L2jLiga unfortunately it doesn't seem to work :(

2020-10-14 14:39 UTC, fox1t commented
> @L2jLiga unfortunately it doesn't seem to work :(

What's the error?

2020-10-14 14:44 UTC, zekth commented
> > @L2jLiga unfortunately it doesn't seem to work :(
> 
> What's the error?

Error was on the `addHook` method not taking the proper overload.

2020-10-14 18:02 UTC, L2jLiga requested changes
Let's add tests first and then check what is better approach

2020-10-14 18:39 UTC, RafaelGSS commented
I tried the approach of overload but seems not works. However, I'll update the PR with this approach to show.

2020-10-14 22:57 UTC, RafaelGSS commented
@L2jLiga @fox1t Attempt added https://github.com/fastify/fastify/pull/2615/commits/1562086f45fa8c8cf962e7c9e354eb0dcb6c7e45

2020-10-15 02:40 UTC, L2jLiga commented
I just checked both approaches with TS playground, [neither separated declaration nor inside one interface seems to work](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoE8QOQbwFDKHIAUUEAjgFzIDyARgFYQJgA0yZAztfUy+wBMA9iAjVi0KEKgB+anBDoAlMgC8APmQA3IcAFLqOvQG48AXzyhIsRCgCCnTNnxESZKrUbM2HCN098YAbIAApSALbAnBAAPEYCyAA+yKJa0OqmFpbg0PBIyHYCAgASQkIA1rgERHBFpRXEABZl5dQA5CIAShQArn5gbeyNCgIANtDUDk5JaE7B8XjVhLUlLQBMTS3tXb39g8jDIGMTBY5Y87oCS8gr9eUbzRXbIN3kfZwDQyPjUNQY54ZLotXLcWgBmTZPZAdF67D77Q7HX6zAHaIEgurgyGtaE7N57L5HH6TM4IC56cyLcZgZDAcIAB1GalwZhunAKmIqiwA9NzkABVEDAESWBmjAB0oIaMNe70+bgo7C4ghEEHJCQ0uGQwlExBUZiUpjpjMlnPKxBlcPlcFJCvISr8wTCQki0Til00mpcRC4xl85EyhtFJql5st+Ph7Bt01Iit8nBVoidESisXins03sIOogesDpjwvNO0xgwCgH2DEtDG3Dcv2sft8cTasBejUme1qr1yANRrFptWFRreLrUdtDYdnGTLtT7r0Gaqrl9-vzlYHd2HsIj1vH7knzenrrTHvbi6IObz5iDhb5-2wpfLYDXoYhtYJdv3naTrY1HYv+qDY0qzNV8R3faMsA-eND1ndNTyzeM-XcVcgPXLE30jNkYz3JsvxbUIUzdOCvWuf9VyAA)

2020-10-15 06:45 UTC, zekth commented
> I just checked both approaches with TS playground, [neither separated declaration nor inside one interface seems to work](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoE8QOQbwFDKHIAUUEAjgFzIDyARgFYQJgA0yZAztfUy+wBMA9iAjVi0KEKgB+anBDoAlMgC8APmQA3IcAFLqOvQG48AXzyhIsRCgCCnTNnxESZKrUbM2HCN098YAbIAApSALbAnBAAPEYCyAA+yKJa0OqmFpbg0PBIyHYCAgASQkIA1rgERHBFpRXEABZl5dQA5CIAShQArn5gbeyNCgIANtDUDk5JaE7B8XjVhLUlLQBMTS3tXb39g8jDIGMTBY5Y87oCS8gr9eUbzRXbIN3kfZwDQyPjUNQY54ZLotXLcWgBmTZPZAdF67D77Q7HX6zAHaIEgurgyGtaE7N57L5HH6TM4IC56cyLcZgZDAcIAB1GalwZhunAKmIqiwA9NzkABVEDAESWBmjAB0oIaMNe70+bgo7C4ghEEHJCQ0uGQwlExBUZiUpjpjMlnPKxBlcPlcFJCvISr8wTCQki0Til00mpcRC4xl85EyhtFJql5st+Ph7Bt01Iit8nBVoidESisXins03sIOogesDpjwvNO0xgwCgH2DEtDG3Dcv2sft8cTasBejUme1qr1yANRrFptWFRreLrUdtDYdnGTLtT7r0Gaqrl9-vzlYHd2HsIj1vH7knzenrrTHvbi6IObz5iDhb5-2wpfLYDXoYhtYJdv3naTrY1HYv+qDY0qzNV8R3faMsA-eND1ndNTyzeM-XcVcgPXLE30jNkYz3JsvxbUIUzdOCvWuf9VyAA)
> 
> _update_: seems like I found [possible solution](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gdgJQgRwK4QM7ADwBUB8UAvFLlBAB7ARwAmGUAFAHSsCGATgOYYBcUbOCADaAXQCUxQoJAAoKAH4oSYKg5xc4CHkKVqdBgAUOAewC2ASwzaLcAGYQOUQ-nlRFTDin4wARgCsIAGNgABooLz5YAODgSSJCY3MrbRc3KH5GL2QfGJDwyNzA-KhaEzgIfgARcogAMTh4wgA3EwtaN35cAG5ZWVBIKBqKhuImR1MOBX4ZJqhW9t7ZW2oOOzYg6ABBWloACRMTAGsoAG90gV2D47xyKhp6JlZmTh4ZoTE5hdp8RgALQ5HfgAcnKSDQmGAwPCf0EtAANo4fIgUOgsDpxPxvrIAL59RHAKAWMxgeFjU44gQMHb7QF9AD09NIWiJ9kcNE2yxJ8JeV0BjFBKIhWGhnhQBUw4TKFUx8zatCkZ1KtUYkhx4l6xNJvNpxwFYNRkNFbAwIDgQTFyAlGFlSUs1mw30ICTOF0i3QiKF66s13J11yO+qFaKh4RNZotWXFnowUtqc3O7nc0ogqu9GqAA), @fox1t wdyt?

If you try this in the project the issue comes at the end of the different hooks. Like the `preValidation` hook has an error related to `onClose` which is totally out of scope. I'll reproduce and share the code.

2020-10-15 07:19 UTC, L2jLiga commented
> ```
> 'req' is declared but its value is never read.
> 'res' is declared but its value is never read.
> 'req' is declared but its value is never read.
> 'res' is declared but its value is never read.
> ```

Yeah, it's just a warning that they're not used hence can be deleted


> ```
> Argument of type '(req: Object, res: Object, done: DoneFn) => Promise<void>' is not assignable to parameter of type '(req: Object, res: Object) => Promise<void>'
> ```
> Means like the type mapping is not working properly

This is expected due to [documentation](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#hooks)
> **Notice:** the `done` callback is not available when using `async`/`await` or returning a `Promise`. If you do invoke a `done` callback in this situation unexpected behaviour may occur, e.g. duplicate invocation of handlers.

2020-10-15 07:20 UTC, L2jLiga commented
I updated example in playground: [link](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gdgJQgRwK4QM7ADwBUB8UAvFLlBAB7ARwAmGUAFAHSsCGATgOYYBcUbOCADaAXQCUxQoJAAoKAH4oSYKg5xc4CHkKVqdBgAUOAewC2ASwzaLcAGYQOUQ-nlRFTDin4wARgCsIAGNgABooLz5YAODgSSJCY3MrbRc3KH5GL2QfGJDwyNzA-KhaEzgIfgARcogAMTh4wgA3EwtaN35cAG5ZWVBIKBqKhuImR1MOBX4ZJqhW9t7ZW2oOOzYg6ABBWloACRMTAGsoAG90gV2D47xyKhp6JlZmTh4ZoTE5hdp8RgALQ5HfgAcnKSDQmGAwPCf0EtAANo4fIgUOgsDpxPxvrIAL59RHAKAWMxgeFjU44gQMHb7QF9AD09NIWiJ9kcNE2yxJ8JeV0BjFBKIhWGhTAA+tlwhLMOEyhVMfM2rQpGdSrVGJIceJesTSbzaccBWDUZDRRqVUlLNZmJETPDmhANdquXq2HzDYLwWioeE2BgQHAgkwFZaUthvoQEmctTrufrrkcjULvaK-QGg1kUCHTFbtBGVed3O5sr0Yy6eW6DYnPSaRb7-YHPCgCphs8lrOGlZHCIWi5FuhEUKXnbqK+7q8bhT6qemm8gWxhZbU5r33HLHc6Y0A)

2020-10-15 07:22 UTC, zekth commented
> I updated example in playground: [link](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gdgJQgRwK4QM7ADwBUB8UAvFLlBAB7ARwAmGUAFAHSsCGATgOYYBcUbOCADaAXQCUxQoJAAoKAH4oSYKg5xc4CHkKVqdBgAUOAewC2ASwzaLcAGYQOUQ-nlRFTDin4wARgCsIAGNgABooLz5YAODgSSJCY3MrbRc3KH5GL2QfGJDwyNzA-KhaEzgIfgARcogAMTh4wgA3EwtaN35cAG5ZWVBIKBqKhuImR1MOBX4ZJqhW9t7ZW2oOOzYg6ABBWloACRMTAGsoAG90gV2D47xyKhp6JlZmTh4ZoTE5hdp8RgALQ5HfgAcnKSDQmGAwPCf0EtAANo4fIgUOgsDpxPxvrIAL59RHAKAWMxgeFjU44gQMHb7QF9AD09NIWiJ9kcNE2yxJ8JeV0BjFBKIhWGhTAA+tlwhLMOEyhVMfM2rQpGdSrVGJIceJesTSbzaccBWDUZDRRqVUlLNZmJETPDmhANdquXq2HzDYLwWioeE2BgQHAgkwFZaUthvoQEmctTrufrrkcjULvaK-QGg1kUCHTFbtBGVed3O5sr0Yy6eW6DYnPSaRb7-YHPCgCphs8lrOGlZHCIWi5FuhEUKXnbqK+7q8bhT6qemm8gWxhZbU5r33HLHc6Y0A)

My bad you're right. This looks like a good alternative

2020-10-15 07:45 UTC, L2jLiga commented
@RafaelGSS, @fox1t what is your opinion on it?

2020-10-15 09:22 UTC, fox1t commented
@L2jLiga, this is a brilliant solution! Conditional types allow inferring the proper types instead of relying upon intersection/overloading.

As we (re)discovered here, we can't use overloading (type intersection in the types world) for fastify methods. We already encountered this same issue when we decided to deprecate the `FastifyPlugin` interface in favor of `FastifyPluginCallback` and `FastifyPluginAsync`.
@RafaelGSS, can you try to implement what @L2jLiga made in the last playground? I am curious if it works in our codebase. If so, we should start thinking about using it in other places.

2020-10-15 11:47 UTC, L2jLiga commented
@fox1t I played a bit more with types and think you will like this: [link](https://www.typescriptlang.org/play?#code/PTAEGEHsFtsg7UAXAngBwKagGaQE6gCGANsTgK7wDGSAlggM7IAWhSo0hKo5DWVJYgCNCVANZEmxQg3aE8Ac3LQM8dvlB4MScnkRo8MWn1C14sjIQAmAKBCgAKqAC0FanQTJIp+NgwFUTBxDaDswAEFFJldmSEgJSIUGMNAAEQQMADFEGLiJAVIRcRtArHT4QiFiLPgAHgcAGlBEpgwADyRVKyZCeBQAbQBdJvKagD5QAF5HUHbO+G7QAAoAOjX5JIAuUH61lZamsz8CAFVBgEopid6UG1AAfjSM7NmOrqYTu9AH0AAlbV08Ac6Aw9Qmc3eoAACiFjKCbmMvt9HidXvNFpQxPBIAB3eBI74-VbrKLbFqXSYTGFGPi1ABukFoVkRhMJ23gGDp-gJ22JKw2DG2uzWByeHOyFyuoAZTKR23+Oj0wMwYLRkOp0DhtQRRL2ArJUQpVNhtJlzNA7M53O+2wcAG4bI7SmKalNlv5DHh7tsbkbpYyrA6zJ08NhRFhwlYrAAJPKgADeBOsMby9TVCyYfP1RD6Qz9ZrGS1i8W2AHIEP8AI7kDCyUtNVgLap4bblSrVbL1Jr9LTV2tIbYAeSEACsMDQmlo0MQUEPR+OkMMXdkxudtmak1GAKJ4T2x+JpiEZ5Z60k5gaSyn+pmF4tiMsVjB9usN3pWZuthDtmpdnYe-DbDunqTk+NayHOY4TpoGDTrOoDDpBi4jM88CruuAY2AAvo61TsLQ0DTgATG68aYZIzRRvuYiOvYypYEc-iqFQWC4AQyZUTY+FEfylF5Es5bwFWYFIPWywAPq9k0Em1k0VgZGu15WFK8agHJHJLJcmHnEGBHEIRPEpvE-GPs+IlNBpUoanCKxaAwkDEFyGnaZxun6exfECUJ-aiTIKDUMsClWaaAYTFepHOVxekGVRxmCaB3lNL5-lLNJlaBSaoIFspWk6dx7lGZ58UvpIflUOJkmgNJDDpTSmUhdlzn2AAAkgDDOO0mA0O1u4aNglA0PQiACPApbsEIWBJWVb6gKwXKqRkOD4pFbm8QVJnCT5DCleVT5SbZUlqRgfrhQ6zWte1bSdUg3Wem4A2eMNo3QYq+gZTmSmzVgh2LS5eWrWIsVecVKUVVVB3yZZGU2bW9mOeczk0WAdE+McTEsRoyZAfgHHLQZWN4DFhWmaJKX-nge27ZV+3zRyClmspNMYBZOW-VFmM9QTHnrQlAWQ7V0N2Q5TPw7lbPbhzhPc8Vk0BdsQV1TeDWiytVj45LcXE4lW3JWJZM1ZqwWK2FLO4+ze5cxrG1a9tpMcxTaVyxl9L1cbEWuXjEsW0DZklTrZP2xT1WO7VztGxMJ0pC1bUdQuN29f1HhDb0T3jb7U0LDNhBzd92BLe7ZvY17RU+zLtvAVTlNg5Vh3HSzZ3R5dsdk3diegI97BaC9oAGLV72Z9nC256zKtq0Xmvif7FeVoH4O03zBsYALsPC9pQA)

It's universal solution and you have to pass arguments as second generic to `DonableFn<T, Args>`

2020-10-15 14:00 UTC, fox1t commented
> @fox1t I played a bit more with types and think you will like this: [link](https://www.typescriptlang.org/play?#code/PTAEGEHsFtsg7UAXAngBwKagGaQE6gCGANsTgK7wDGSAlggM7IAWhSo0hKo5DWVJYgCNCVANZEmxQg3aE8Ac3LQM8dvlB4MScnkRo8MWn1C14sjIQAmAKBCgAKqAC0FanQTJIp+NgwFUTBxDaDswAEFFJldmSEgJSIUGMNAAEQQMADFEGLiJAVIRcRtArHT4QiFiLPgAHgcAGlBEpgwADyRVKyZCeBQAbQBdJvKagD5QAF5HUHbO+G7QAAoAOjX5JIAuUH61lZamsz8CAFVBgEopid6UG1AAfjSM7NmOrqYTu9AH0AAlbV08Ac6Aw9Qmc3eoAACiFjKCbmMvt9HidXvNFpQxPBIAB3eBI74-VbrKLbFqXSYTGFGPi1ABukFoVkRhMJ23gGDp-gJ22JKw2DG2uzWByeHOyFyuoAZTKR23+Oj0wMwYLRkOp0DhtQRRL2ArJUQpVNhtJlzNA7M53O+2wcAG4bI7SmKalNlv5DHh7tsbkbpYyrA6zJ08NhRFhwlYrAAJPKgADeBOsMby9TVCyYfP1RD6Qz9ZrGS1i8W2AHIEP8AI7kDCyUtNVgLap4bblSrVbL1Jr9LTV2tIbYAeSEACsMDQmlo0MQUEPR+OkMMXdkxudtmak1GAKJ4T2x+JpiEZ5Z60k5gaSyn+pmF4tiMsVjB9usN3pWZuthDtmpdnYe-DbDunqTk+NayHOY4TpoGDTrOoDDpBi4jM88CruuAY2AAvo61TsLQ0DTgATG68aYZIzRRvuYiOvYypYEc-iqFQWC4AQyZUTY+FEfylF5Es5bwFWYFIPWywAPq9k0Em1k0VgZGu15WFK8agHJHJLJcmHnEGBHEIRPEpvE-GPs+IlNBpUoanCKxaAwkDEFyGnaZxun6exfECUJ-aiTIKDUMsClWaaAYTFepHOVxekGVRxmCaB3lNL5-lLNJlaBSaoIFspWk6dx7lGZ58UvpIflUOJkmgNJDDpTSmUhdlzn2AAAkgDDOO0mA0O1u4aNglA0PQiACPApbsEIWBJWVb6gKwXKqRkOD4pFbm8QVJnCT5DCleVT5SbZUlqRgfrhQ6zWte1bSdUg3Wem4A2eMNo3QYq+gZTmSmzVgh2LS5eWrWIsVecVKUVVVB3yZZGU2bW9mOeczk0WAdE+McTEsRoyZAfgHHLQZWN4DFhWmaJKX-nge27ZV+3zRyClmspNMYBZOW-VFmM9QTHnrQlAWQ7V0N2Q5TPw7lbPbhzhPc8Vk0BdsQV1TeDWiytVj45LcXE4lW3JWJZM1ZqwWK2FLO4+ze5cxrG1a9tpMcxTaVyxl9L1cbEWuXjEsW0DZklTrZP2xT1WO7VztGxMJ0pC1bUdQuN29f1HhDb0T3jb7U0LDNhBzd92BLe7ZvY17RU+zLtvAVTlNg5Vh3HSzZ3R5dsdk3diegI97BaC9oAGLV72Z9nC256zKtq0Xmvif7FeVoH4O03zBsYALsPC9pQA)
> 
> It's universal solution and you have to pass arguments as second generic to `DonableFn<T, Args, DoneFn>`

I definitely like this. @Ethan-Arrowood what do you think?
We have to remember that this works only on TS >= 4.0.0, though.
Can you please exlpain line by line `DonableFn` type? I want to add this as reference somewhere. I am adding some comments by my own.

- Why `T extends (...args: any[]) => void` is passed insread of `T extends (...args: any[]) => any`?
- This should not be valid but it is valid `impl2.addHook('onRequest', () => {});` No call to `done()` nor returning promise.

2020-10-15 14:15 UTC, Ethan-Arrowood commented
Ooh very clever. Inferring the function type (callback v async) based on the arguments list. I like it!

2020-10-15 14:21 UTC, L2jLiga commented
> - Why `T extends (...args: any[]) => void` is passed insread of `T extends (...args: any[]) => any`?

 this does not make much sense for example, so no answer 😅 
 
 
 
> - This should not be valid but it is valid `impl2.addHook('onRequest', () => {});` No call to `done()` nor returning promise.

Unfortunately I have no idea how to force ts to check arguments length 😕 

> Can you please exlpain line by line `DonableFn` type? I want to add this as reference somewhere. I am adding some comments by my own.

I think would be better to describe it block by block, I will try provide description asap 🐱

2020-10-15 14:27 UTC, Ethan-Arrowood commented
> Unfortunately I have no idea how to force ts to check arguments length 😕

I don't think you can. I believe TS specifically doesn't do this for some other reasons. Honestly, I can't remember exactly but I do think I explored that rabbit hole in the past and came up empty.

2020-10-15 16:46 UTC, RafaelGSS commented
Hey! I'll update the example tonight with the example provided by @L2jLiga! Seems very interesting!

2020-10-15 17:32 UTC, fox1t commented
@L2jLiga what is `addErrorHook` suppose to be? Shouldn't it be https://www.fastify.io/docs/v3.2.x/Hooks/#onerror?

2020-10-15 19:22 UTC, L2jLiga commented
> I don't think you can. I believe TS specifically doesn't do this for some other reasons. Honestly, I can't remember exactly but I do think I explored that rabbit hole in the past and came up empty.

Then I suggest to don't worry about :)

> Hey! I'll update the example tonight with the example provided by @L2jLiga! Seems very interesting!

Cool! Thanks dude!

> **@L2jLiga what is `addErrorHook` suppose to be? Shouldn't it be https://www.fastify.io/docs/v3.2.x/Hooks/#onerror?**

Just an example how it can be used for hooks with different arguments length, does not related to fastify itself

2020-10-16 02:06 UTC, RafaelGSS commented
@L2jLiga I have failed to update the `onRequestHookHandler` with these solutions. Can you update one type on this branch? Not sure about the solution

2020-10-16 08:05 UTC, fox1t commented
@mcollina we are waiting for the description of the code provided by @L2jLiga. After that, we can try to integrate his solution in fastify types. If it works we finally have a way of expressing polymorphic methods and it would be an awesome achievement.
Again, this solution would be only compatibile with TS >= 4.0, though.

2020-10-16 08:06 UTC, fox1t requested changes
Try @L2jLiga solution :)

2020-10-16 10:45 UTC, L2jLiga commented
I tried to explain, [link](https://www.typescriptlang.org/play?#code/PTAEGEHsFtsg7UAXAngBwKagGaQE6gCGANsTgK7wDGSAlggM7IAWhSo0hKo5DWVJYgCNCVANZEmxQg3aE8Ac3LQM8dvlB4MScnkRo8MWn1C14sjIQAmAKBCgAKqAC0FanQTJIp+NgwFUTBxDaDswAEFFJldmSEgJSIUGMNAAEQQMADFEGLiJAVIRcRtArHT4QiFiLPgAHgcAGlBEpgwADyRVKyZCeBQAbQBdJvKagD5QAF4bUFB7AFFzXSwkVnYHAGUeE2xKGnpEGUcZx1B2zvhu0AAKADp7+SSALlB++9uWprM-AgBVQYAlFMJr0UDN7OBmBhxKAAO5Q1b+UDSWRERTKVTqbCgBS0ABuqjc+08xg4XFAQjKGWyMwA-GlqYhzl0mL8TnMwABJbEoDBMWH8KEw+HaKEELQ6PTIdBYUkGIwmDTwSBIdn0gBK2l08AcMvqE2ZlyYAAUQsYMLVQWN2RzQNzNFqpaVTEx5dBzXCsKwCV5QFQhRJSSi5OiVGomJQxMrYfAbfTfmcOiyePAo5AYzbZvZ7bR2JHo4hEYgBQ7JYgqPgtAw0AgrGYFKAGLQFBVJRhM6B6XcHlEXi0gZMJqaFRa8ZBaFZrbNp7ac+w0zGbrgCO1CNA0NVQKwen1pZggSWJdrQPAMASAt4DGfMSxSQI+B2XqfzzaFsQTIfHYgGOQW2xlnCubMAyp7ZJIyIyCGShhqqM4vN2tyPAwLxvPcnwgTUgLAqAY4TuyLyamWuqYPqiYXFcw7unwlp9BMXbvEhfZRAOQ5mtRuGTqAT7XngJzZtimygGgMhMMqiC7O4By+kcThFp6oAAFa8OwR5SrJl5aASahnHghh4MkswvA4ADcNhmc6oxgZMNz+HptIvKCLE4eOVimWYnR4NgohYOEVhWAAEnkoAAN42tYAV5PUZHJghjFEH0QxORxYzXLE8QvAA5AgmoAI7kHySAZU0rCXNUeAvOUlTVNk9RNP0Wh5QVLwAPJCAp0JIE0WgbigLVtR1wwYdkYwAi8HFhX58y6fggXxFFhpXLFvbxQMWGDs5E4pWlYiZdlGCNbIRVbr0VhlRVCBVTUtWvLZ+AvFNeldft+WyH17U0E9PVvQNIyMiNY0uTYAC+ZnVOwtDrsQABMUwhUD4G+RF8RmfYxGyr4-iqFQWDLkQfmzWINgQxuUOIfjeTXFl8C5S9hVNNcAD6DVNEzfJNFYGSjRtVjYcFoAc6e1xAkDAJuZDpPhQTlN7QddM3E5lHmrcVaQMQBJC6LRPi2TSNiNL1PPQVR0yCg1Dyy8ivsS5EzrcFItiyTOtS1TNNG00Jtm4zDVc5bo7W7z9ta47ksUy7huHe7DCm1QNyszlLNVj7bF+5tAea-YAACSAMM47SYDQufTQQEnEuWvQZewlKSNH8U896WACzjsbE9DTuhzLtPG1HntxwnbOgAzjdOXb6dgFnOd5x1hd6USHhl-AFelseboeidx0+o3ODN9rIfxPrrsR7HzMD1WLND9hvvK3yqvqwCmso2AaM+D8WM4xo4UPTNeRB63H9F87Hc3ax1ungPu8cT79yHgDCcvN+YZCFqAQOLcJaTX-u3A2ssjoIPWpfFWasMAawdr-VBekAEYM7pHGuQsLbJ1qMlNORCUFWE-ngMhB85YexjozEBScRx0P9rbJBO8SFfz3mHTBlCe4gLAbwqiKdOKCM1sgnWLC2Hhw4d3LhDNpEQPAazBgsjzT8NToo0ymds65zaPnJA08NAlznn6culcsCcNruvBuGQt4-yYao9B7Cu5UO0UXMBfcGBn05gwlI49LHWNscXPYDiBALxUl+ISyc3H1zgaeLxyi-6kL8eorBQTHq6NCeE08Ctk5XwYDfAhd9jJAA)

2020-10-16 10:52 UTC, L2jLiga commented
> If it works we finally have a way of expressing polymorphic methods and it would be an awesome achievement.
Again, this solution would be only compatibile with TS >= 4.0, though.

I'm sure it will work but same time bit worried about users with TS < 4.0 (personally I prefer to always update to latest version but.....)

2020-10-16 11:17 UTC, L2jLiga commented
Hmm, it seems like [`tsd`](https://github.com/SamVerschueren/tsd) does not support TS 4.0 yet :(

2020-10-16 11:18 UTC, L2jLiga commented
btw I pushed commit ahead with usage example (CI will fail)

2020-10-16 12:52 UTC, zekth commented
Issue might be related to eslint:
```console
> eslint -c types/.eslintrc.json types/**/*.d.ts test/types/**/*.test-d.ts


/home/runner/work/fastify/fastify/types/callback-or-promise.d.ts
  0:0  error  Parsing error: Cannot read property 'map' of undefined

/home/runner/work/fastify/fastify/types/hooks.d.ts
  0:0  error  Parsing error: Cannot read property 'map' of undefined
```
The upgrade of it might be needed

2020-10-16 14:18 UTC, fox1t commented
I am not getting where these errors came from? Do they change the default settings for ts eslint?

2020-10-16 14:27 UTC, zekth commented
> I am not getting where these errors came from? Do they change the default settings for ts eslint?

The error of `Cannot read property 'map' of undefined` are introduced by the change of AST tree in typescript v4, and it has been fixed in https://github.com/typescript-eslint/typescript-eslint/releases/tag/v4.0.0

The errors prompted after the upgrade are just default eslint rules update / change.

2020-10-16 14:30 UTC, fox1t commented
> > I am not getting where these errors came from? Do they change the default settings for ts eslint?
> 
> The error of `Cannot read property 'map' of undefined` are introduced by the change of AST tree in typescript v4, and it has been fixed in https://github.com/typescript-eslint/typescript-eslint/releases/tag/v4.0.0
> 
> The errors prompted after the upgrade are just default eslint rules update / change.

Yea, I was referring to the errors after upgrade. I think we can open a new PR to handle the upgrade and then merge it also here to work on this PR.

2020-10-17 05:31 UTC, L2jLiga commented on types/callback-or-promise.d.ts
> +    : T
I'm unsure why but this does not work when I use never here

2020-10-17 07:50 UTC, L2jLiga commented
> > Unfortunately I have no idea how to force ts to check arguments length 😕
>
> I don't think you can. I believe TS specifically doesn't do this for some other reasons. Honestly, I can't remember exactly but I do think I explored that rabbit hole in the past and came up empty.

@Ethan-Arrowood I can! [link](https://www.typescriptlang.org/play?#code/PTAEGEHsFtsg7UAXAngBwKagGaQE6gCGANsTgK7wDGSAlggM7IAWhSo0hKo5DWVJYgCNCVANZEmxQg3aE8Ac3LQM8dvlB4MScnkRo8MWn1C14sjIQAmAKBCgAKqAC0FanQTJIp+NgwFUTBxDaDswAEFFJldmSEgJSIUGMNAAEQQMADFEGLiJAVIRcRtArHT4QiFiLPgAHmzQDAAPJFUrJgAKADoe+SSALiJ4FABKUABeAD4hlAAaUESmZtb4dpmAbQBdefKaxpa2pnXCYc3p8ZtQUHsAcW1QBVoAN1VQWPiiRWVVJCZSoasmm0ukQpUuoAay0OoG6vSigzMfgIiW+agYYymPiRoAASg5wVd7OBmBhxECdHpkOgMATQAB+XFOKGrJgABRCxgwABlaGIMLVEf5QKzJrTCWAccDKTIUNQ3nlQAxaAoKhSaVcNfSYT0un0GINFhjpuyjHxaiKxdcwMTSRIkKx2AxZVR5R9WEsmpgaBhAYQ4JR1NhPkoVGjLQavqHfvsVmt1jrFvNKGJ4JAAO7wTaW8WgACSQYY3i0FMQVHwWgYaAQVjMCkVytVunVmo1DNhuvhoHjPUToB1u2ymyNoCekFothbGvsAHl7f405zQPAMC88NnQINl6vwfYHNPUtOEfAXrJlWwsGnmNw01hlz6vOSQRDECStD4LNZQJAg1v-ODBtkNglNSaQZA04wwv4hh4HSgwnKMEzTKO44ANw2GYrR4NgohYOEVhWAAEgqADetLWIReS1EyBwstqcIDDMw7IVYkwdO8YiDAA5AgkoAI7kBgsicfMrCrNUeCDOUlTVNkVHzOsWj8YJSCDAA6hgQgAMqQOI2jzFoaDECgakadpulINsXZWBkklgZmkwjIMzFkfhACieDQUR8RUTG0LtnqcHDExY4sWxeRcTxGBKUJIknFY4m2RUVQ1HJXZQfggzudB+lRQJsiDNOQgAFakkgOWGcZoCFSVNCWes1nLolNRnI5I4hTYAC+QHVOwtDQIZABMEygMRHWSAs+FeWIQG7iBgpaNQWC4AQ5FTSkAACvzOM0XpINtHkaE6crYJQND0Ig0C8OwrAvKADX8IIRTTX1g26pNeQdNx8B8XlSDCTCAD6inzEDgmtcxiEjVcHUjGhL3EANb0UfEn2RdFf3zB0oO8SDFbzPd4MhZDxF3RkHRjDDaH2JtDDbZ6pX7dBirOm4Z2eAI8CcddhC3eRtAeBUZBoPIfraH+8OI6tH1fT9yn-VjwOgKDDD4xkuM+pQVgnEghPjsTpPLuToCU+h-UI0jU2o99uVy5jw4mtAnJdBWkDEC85Ow6br1SyjMs2zFkgs+TgwO5ytTMec0yjZ7EsW9LaO-f9MpygrUWtaHZoR8TJuxz7YhW7LAfJy6qc40rFbpxymchZHI0m9TW07Qz6UECd7jnaAHNc6AQhYMXAJvDzWD3Tg8Be+becF-7GOByn2PqyrSsE9nnsN7TTc0IzGht2zpYnN3vezy6cWD7dI-YGPufvb7Ce24DivKyDy+YhnGDO4JrvuyMnszWADhzb4fwqgqBLQ0ORLK+A1pXysBAvAls-bo3lgDFu6sy6PwNhgXWgJMQk3ukbHOZtJZuQOnA+O1tEF20hq-d+hY3YYA9nDQhSNYHwNvkXI6JdK6mn5FnHBBDvbEM8mQwuM9+5Yxblwx21dxy12jowgRMCSGsPIYneYYjkEkNQZIsOvCo78InoIyBwjp5Jw4YDFB5cooL20dIliK8qZgBpnTXaW9W6nQFp3fe7BD79xPjdYeGRR7jyIYooRN8VF33URY+eljF4A2fno1ejjG7003i3VmHiu7sGLE+Aw3CB7+IwUE6BLDjEUPMZoyxaC8ZLwyPbKub8XZ0IYUAA)

2020-10-21 17:48 UTC, fox1t commented
> > > Unfortunately I have no idea how to force ts to check arguments length 😕
> > 
> > 
> > I don't think you can. I believe TS specifically doesn't do this for some other reasons. Honestly, I can't remember exactly but I do think I explored that rabbit hole in the past and came up empty.
> 
> @Ethan-Arrowood I can! [link](https://www.typescriptlang.org/play?#code/PTAEGEHsFtsg7UAXAngBwKagGaQE6gCGANsTgK7wDGSAlggM7IAWhSo0hKo5DWVJYgCNCVANZEmxQg3aE8Ac3LQM8dvlB4MScnkRo8MWn1C14sjIQAmAKBCgAKqAC0FanQTJIp+NgwFUTBxDaDswAEFFJldmSEgJSIUGMNAAEQQMADFEGLiJAVIRcRtArHT4QiFiLPgAHmzQDAAPJFUrJgAKADoe+SSALiJ4FABKUABeAD4hlAAaUESmZtb4dpmAbQBdefKaxpa2pnXCYc3p8ZtQUHsAcW1QBVoAN1VQWPiiRWVVJCZSoasmm0ukQpUuoAay0OoG6vSigzMfgIiW+agYYymPiRoAASg5wVd7OBmBhxECdHpkOgMATQAB+XFOKGrJgABRCxgwABlaGIMLVEf5QKzJrTCWAccDKTIUNQ3nlQAxaAoKhSaVcNfSYT0un0GINFhjpuyjHxaiKxdcwMTSRIkKx2AxZVR5R9WEsmpgaBhAYQ4JR1NhPkoVGjLQavqHfvsVmt1jrFvNKGJ4JAAO7wTaW8WgACSQYY3i0FMQVHwWgYaAQVjMCkVytVunVmo1DNhuvhoHjPUToB1u2ymyNoCekFothbGvsAHl7f405zQPAMC88NnQINl6vwfYHNPUtOEfAXrJlWwsGnmNw01hlz6vOSQRDECStD4LNZQJAg1v-ODBtkNglNSaQZA04wwv4hh4HSgwnKMEzTKO44ANw2GYrR4NgohYOEVhWAAEgqADetLWIReS1EyBwstqcIDDMw7IVYkwdO8YiDAA5AgkoAI7kBgsicfMrCrNUeCDOUlTVNkVHzOsWj8YJSCDAA6hgQgAMqQOI2jzFoaDECgakadpulINsXZWBkklgZmkwjIMzFkfhACieDQUR8RUTG0LtnqcHDExY4sWxeRcTxGBKUJIknFY4m2RUVQ1HJXZQfggzudB+lRQJsiDNOQgAFakkgOWGcZoCFSVNCWes1nLolNRnI5I4hTYAC+QHVOwtDQIZABMEygMRHWSAs+FeWIQG7iBgpaNQWC4AQ5FTSkAACvzOM0XpINtHkaE6crYJQND0Ig0C8OwrAvKADX8IIRTTX1g26pNeQdNx8B8XlSDCTCAD6inzEDgmtcxiEjVcHUjGhL3EANb0UfEn2RdFf3zB0oO8SDFbzPd4MhZDxF3RkHRjDDaH2JtDDbZ6pX7dBirOm4Z2eAI8CcddhC3eRtAeBUZBoPIfraH+8OI6tH1fT9yn-VjwOgKDDD4xkuM+pQVgnEghPjsTpPLuToCU+h-UI0jU2o99uVy5jw4mtAnJdBWkDEC85Ow6br1SyjMs2zFkgs+TgwO5ytTMec0yjZ7EsW9LaO-f9MpygrUWtaHZoR8TJuxz7YhW7LAfJy6qc40rFbpxymchZHI0m9TW07Qz6UECd7jnaAHNc6AQhYMXAJvDzWD3Tg8Be+becF-7GOByn2PqyrSsE9nnsN7TTc0IzGht2zpYnN3vezy6cWD7dI-YGPufvb7Ce24DivKyDy+YhnGDO4JrvuyMnszWADhzb4fwqgqBLQ0ORLK+A1pXysBAvAls-bo3lgDFu6sy6PwNhgXWgJMQk3ukbHOZtJZuQOnA+O1tEF20hq-d+hY3YYA9nDQhSNYHwNvkXI6JdK6mn5FnHBBDvbEM8mQwuM9+5Yxblwx21dxy12jowgRMCSGsPIYneYYjkEkNQZIsOvCo78InoIyBwjp5Jw4YDFB5cooL20dIliK8qZgBpnTXaW9W6nQFp3fe7BD79xPjdYeGRR7jyIYooRN8VF33URY+eljF4A2fno1ejjG7003i3VmHiu7sGLE+Aw3CB7+IwUE6BLDjEUPMZoyxaC8ZLwyPbKub8XZ0IYUAA)

OK `Arguments extends [...Args, unknown]` too much also for me XD

Well done, though!

2020-10-21 17:50 UTC, Ethan-Arrowood commented
This is very impressive! good work @L2jLiga

2020-10-21 20:02 UTC, RafaelGSS commented
eslint updated! I'll pull on this branch

2020-10-24 03:11 UTC, RafaelGSS commented
Fixed (Sorry for the late - busy week). If the implementation is accepted I'll change every hook.

2020-10-24 03:26 UTC, RafaelGSS commented
@L2jLiga Unfortunately the implementation seems not to work on `tsd` checks. Check the `tsd` errors on `callback-or-promise.d.ts` and `hooks.test-d.ts`.

2020-10-24 07:40 UTC, L2jLiga commented
> @L2jLiga Unfortunately the implementation seems not to work on tsd checks. Check the tsd errors on callback-or-promise.d.ts and hooks.test-d.ts.

@RafaelGSS  I mentioned this [here](https://github.com/fastify/fastify/pull/2615#issuecomment-709985116) and already thinking how we can fix it 🤔

2020-10-24 07:54 UTC, L2jLiga commented
Here's fix:

https://github.com/SamVerschueren/tsd/pull/83

2020-10-26 15:53 UTC, fox1t commented
I think we should just wait for the TS 4.1 if we want to implement this. It is a breaking change for TS users.

2020-10-26 15:58 UTC, RafaelGSS commented
@fox1t This does not change only on fastify side? IMHO we should land this fix without the overload/conditional type and after the `tsd` merge, we add support for it.

2020-10-26 16:00 UTC, fox1t commented
Yes. Sorry for the confusion: I meant that we should wait to land the "overload/conditional type" part and go on with the current fix for the moment.

2020-10-26 21:31 UTC, L2jLiga approved these changes
Ok, works for me :)

2020-10-28 08:29 UTC, fox1t approved these changes
LGTM!

2020-10-29 07:36 UTC, zekth approved these changes
lgtm

2020-10-29 22:37 UTC, RafaelGSS commented
@Ethan-Arrowood Have any concerns about? I will land tomorrow.

2020-10-29 23:04 UTC, Ethan-Arrowood approved these changes
lgtm :) great work everyone!

2020-10-30 12:07 UTC, merged