Added (probably) missing line for http2 server
fastify/fastify pull request #2681
Opened 2020-11-10 17:19 UTC by Jelenkee

I guess when the graceful closing for http2 was [added](https://github.com/fastify/fastify/commit/d0c976e82549488ecd27c17421cd3b51264468de#diff-1b48bb429de959672dadab9c87c215e19177dd70e3bd932d131ce74294c44cd5R27), it was simply forgotten to add this line for https too.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2020-11-10 17:36 UTC, L2jLiga approved these changes
lgtm

2020-11-10 19:45 UTC, mcollina requested changes
Can you please add a unit test?

2020-11-10 19:45 UTC, mcollina commented
Good spot!

2020-11-10 20:44 UTC, Jelenkee commented
Mmh.. There is already a test with HTTPS and HTTP2. And there are these [tests](https://github.com/fastify/fastify/blob/master/test/http2/closing.test.js#L106) for HTTP2, but these are skipped due to a bug in node. And I don't know how to test this sessionTimeout anyway because I didn't understand what it does. 🤔🤪

2020-11-28 10:17 UTC, Eomm commented
That test is skipped only per node <8 (and that check could be removed since we support >=10)

That test cover `http2` only and not `http2+TLS` so you need to add the `https` config - there are already some example in the code

2020-12-22 10:59 UTC, Jelenkee commented
I still don't understand these session timeouts for http2. Can someone add the requested unit test who has sufficient knowledge of that topic?

2020-12-22 14:40 UTC, mcollina commented
@Jelenkee you just need to duplicate https://github.com/fastify/fastify/blob/854b115effce204ef8d7eca5d77049f337ba3385/test/http2/closing.test.js#L107-L120 for HTTP2 with `https`.

2020-12-28 14:05 UTC, mcollina approved these changes
lgtm

2020-12-28 14:05 UTC, merged