fix: throw in `onSend` causes fastify to not respond
fastify/fastify pull request #2695
Opened 2020-11-18 14:38 UTC by AyoubElk

fixes the issue described in #2692 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2020-11-18 15:01 UTC, mcollina reviewed
thanks, just one nit!

2020-11-18 15:01 UTC, mcollina commented on lib/hooks.js
> +      next(error)
```suggestion
      next(error)
      return
```

2020-11-18 17:48 UTC, RafaelGSS approved these changes
LGTM.

2020-11-18 18:07 UTC, AyoubElk commented
This issue mentions the `onSend` hook, I'm still not very familiar with the codebase but I think maybe a similar fix is needed in `hookRunner` and `hookIterator` functions which are used for other hooks?

Let me know if you agree, and if I missed some other function that needs the fix as well.

2020-11-18 18:24 UTC, delvedor requested changes
This should be fixed also for every other hook :)
https://github.com/fastify/fastify/blob/2f46d9a4b957a9b1c30d380eb2df9e2fd374a4ce/lib/hooks.js#L162

2020-11-20 19:28 UTC, Eomm approved these changes

2020-11-20 23:54 UTC, AyoubElk commented
Just found out that preParsing hooks have a separate runner, I added a fix for that as well.

2020-11-21 09:26 UTC, mcollina commented
@delvedor ok for you now?

2020-12-14 15:48 UTC, Ethan-Arrowood approved these changes

2020-12-15 13:06 UTC, fox1t approved these changes

2020-12-16 08:08 UTC, delvedor approved these changes
LGTM

2020-12-16 08:12 UTC, merged