CSRF Guide
fastify/fastify pull request #2814
Opened 2021-01-23 13:32 UTC by xhlika

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-01-23 18:48 UTC, zekth requested changes
This is a pretty complete guide. I'd add an example on how to fix it using `fastify` echosystem code like https://github.com/fastify/fastify-csrf .

Also couple remarks on formatting.

(i  can't verify grammar as i'm not english native0

2021-01-23 18:48 UTC, zekth commented on docs/CSRF_guide.md
> +## Be aware of the danger: Cross-Site Request Forgery (CSRF)
```suggestion
### Be aware of the danger: Cross-Site Request Forgery (CSRF)
```

2021-01-23 18:48 UTC, zekth commented on docs/CSRF_guide.md
> +## CSRF Origins
```suggestion
### CSRF Origins
```

2021-01-23 18:48 UTC, zekth commented on docs/CSRF_guide.md
> +## How does CSRF exactly work?
```suggestion
### How does CSRF exactly work?
```

2021-01-23 18:48 UTC, zekth commented on docs/CSRF_guide.md
> + ## Impact of CSRF attacks
```suggestion
 ### Impact of CSRF attacks
```

2021-01-23 18:48 UTC, zekth commented on docs/CSRF_guide.md
> + ## Most popular anti-CSRF defenses
```suggestion
 ### Most popular anti-CSRF defenses
```

2021-01-23 18:48 UTC, zekth commented on docs/CSRF_guide.md
> +  ##  Great does not mean perfect!
```suggestion
###  Great does not mean perfect!
```

2021-01-23 18:48 UTC, zekth commented on docs/CSRF_guide.md
> +                                                                                                                      -Author: Xhelal Likaj (xhelallikaj20@gmail.com)
Not sure we sign the documents in the docs.

2021-01-23 19:04 UTC, xhlika commented on docs/CSRF_guide.md
> +                                                                                                                      -Author: Xhelal Likaj (xhelallikaj20@gmail.com)
Hmm, sorry, I thought this was more of a blog regarding CSRF than actual documentation. I had a talk with Matteo Collina about this. I can remove if this will go down as a documentation rather than a blog.

2021-01-23 19:08 UTC, xhlika commented on docs/CSRF_guide.md
> +                                                                                                                      -Author: Xhelal Likaj (xhelallikaj20@gmail.com)
As for the grammar, I am not a native English spear either but I am pretty confident about it. Nevertheless, someone can double check it

2021-01-23 20:09 UTC, jsumners requested changes
I don't see what purpose this serves in the core repository. Fastify core does not provide any CSRF mitigation features. That is the domain of the `fastify-csrf` plugin. Further, this "guide" is a general dissertation on the concept of CSRF. Skimming through it, I do not see any way in which this guide is related to Fastify and Fastify core's relation to CSRF.

IMHO, this is no better than copying and pasting a Medium (or some other blog site) post into a project that is tangentially related to the topic.

I am 👎

2021-01-23 20:14 UTC, xhlika commented
I spend 8 months researching CSRF and coming up with this compressed information about all threat vector that can be used to exploit or trigger CSRF attacks. I spend most of my day off today coming up with this, explaining the best I can to raise the awareness and the quality of the documentation you have regarding CSRF, so please don't consider my work a mere copy/paste from Medium. I did a scientific work and here I am sharing a part of it. 

P.S: I was asked to do this by someone on your security team and here you have it. if I wanted to write a Medium blog, I could have done it elsewhere...

2021-01-23 20:18 UTC, jsumners commented
My point is that this document is not related to this project. It is written _as a_ general weblog post and would be _more appropriate as written_ on such a site. I _did not_ assert that you copied it from anyone or anywhere else.

My assertion is that any "documentation" we include in the Fastify project _should relate to Fastify_.

2021-01-24 12:12 UTC, Eomm reviewed
I agree with @jsumners and I would move this great article to `fastify-csrf`

Anyway, I think we should help the community and spread these security aspects.
So what do you think about creating a `docs/Guides.md` or `docs/SecureYourServer.md` that links those resources in the fastify org that a new software developer could learn from?
(ie: fastify-csrf, fastify-helmet etc..)

2021-01-24 12:12 UTC, Eomm commented on docs/CSRF_guide.md
> +* Incorrect SOP relaxation (e.g. faulty CORS)**: is also a possible attack vector that can lead to CSRF token leakage. An over-permissive CORS that sets the response headers Access-Control-Allow-Orig
What does it mean those `**`?

2021-01-24 12:12 UTC, Eomm commented on docs/CSRF_guide.md
> +Note: SameSite cookies appear to be the next attempt to prevent CSRF attacks. Although SameSite raises the bar for attackers, it is not perfect as well. For example, SameSite: Lax does not completely
This link `[SameSite can also be circumvented with other means]` doesn't work

2021-01-24 12:12 UTC, Eomm commented on docs/CSRF_guide.md
> +                                                                                                                      -Author: Xhelal Likaj (xhelallikaj20@gmail.com)
It renders as a block code due the spaces, maybe a `<div>` would fix it

2021-01-24 12:41 UTC, Fdawgs commented
@Eomm OWASP provides a lot of useful guides/cheat sheets for security, so it seems a bit redundant to have that content duplicated into Fastify repos?

The guides on OWASP could do with an update though as, when node web apps are referenced, it only provides links and examples using Express middleware and not Fastify plugins.

I'm happy to go through their guidance and make the required pull requests if needed.

2021-01-24 13:54 UTC, Eomm commented
> @Eomm OWASP provides a lot of useful guides/cheat sheets for security, so it seems a bit redundant to have that content duplicated into Fastify repos?
> 
> The guides on OWASP could do with an update though as, when node web apps are referenced, it only provides links and examples using Express middleware and not Fastify plugins.
> 
> I'm happy to go through their guidance and make the required pull requests if needed.

I didn't want to duplicate the content but I was thinking about to a kind of "awesome list" of security concern tailed to the fastify ecosystem.

In my mind, I was thinking this:

```
# Security aspect you should know

- CSRF: the cross site request forgery can be manage with `fastify-csrf` plugin. Learn what is this attack [here](link to this guide.md)
- Helmet: protect your web application setting the right response headers with `fastify-helmet`. 
```

2021-01-24 14:00 UTC, xhlika commented
I find the idea great tbh. A part of my (private) vulnerability report included some issues that could be easily fixed with Helmet. And OWASP is already cited in my CSRF guide (links lead to multiple of its articles, to the the relevant content). Let me know what you all agree to and I can move things around.

2021-01-24 14:06 UTC, jsumners commented
> So what do you think about creating a `docs/Guides.md` or `docs/SecureYourServer.md` that links those resources in the fastify org that a new software developer could learn from?

We have a "Guides" section being created in #2610. But they should still be related to Fastify itself. They are meant to be informal tone documents instead of reference tone documents.

2021-01-25 06:53 UTC, delvedor reviewed
Great work!
I agree with @jsumners that this document should live in `fastify-csrf`, as fastify is a general-purpose framework, that can be easily used for internal services authenticated with Bearer auth for example.

2021-01-25 20:09 UTC, mcollina commented
I think this will be great to live in the docs of the website. It's hardly discoverable inside fastify-csrf.

2021-01-25 20:11 UTC, zlarumbe commented
El lun., 25 de enero de 2021 2:10 p. m., Matteo Collina <
notifications@github.com> escribió:

> I think this will be great to live in the docs of the website. It's hardly
> discoverable inside fastify-csrf.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fastify/fastify/pull/2814#issuecomment-767082197>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJXTQT7LLL356RFI7C3OQGTS3XFZZANCNFSM4WPV6QAQ>
> .
>

2021-01-27 12:27 UTC, kamikazechaser commented
This is a good write up. It should live in the main docs under a `Security best practices` category. However the entirety of it will bloat the documentation. Instead, a code example of how fastify eliminates this should be used along with a summarized version of this. The verbose description should probably reside somewhere else.

2021-01-27 12:33 UTC, Fdawgs commented
>
> My point is that this document is not related to this project. It is written _as a_ general weblog post and would be _more appropriate as written_ on such a site. I _did not_ assert that you copied it from anyone or anywhere else.
> 
> My assertion is that any "documentation" we include in the Fastify project _should relate to Fastify_.

@jsumners is right, whilst good it is a blog post.

It's even referenced in another pull request to another framework as such: https://github.com/vertx-web-site/vertx-web-site/pull/91

2021-01-27 14:42 UTC, xhlika commented
It is referenced in another framework because they asked me to write it as well. I am the author of it as well. The security topics are not scoped to Fastify alone but to web itself. I cannot write 2 different articles explaining the same attack vectors. Instead. this can be enriched with fastify-based examples (as rightfully suggested by some of you) and to me it would look like a very good documentation both theoretically and practically. 

However, the decision rest on you. I wrote the guide because I was asked to and did my best to cover as many vectors as possible, as briefly as possible. I am not aware of any blog covering them all together, especially seen in the CSRF context.

2021-03-30 12:55 UTC, jsumners commented
Closing due to inactivity and a lack of response to issues raised.

2021-03-30 12:56 UTC, closed without merging