feat: add ts-standard
fastify/fastify pull request #2893
Opened 2021-03-04 08:35 UTC by zekth

2021-03-04 08:42 UTC, mcollina approved these changes
lgtm

2021-03-04 08:43 UTC, mcollina commented
There are still linting changes

2021-03-04 09:00 UTC, zekth commented
@mcollina yes, i'm wondering about overrides. If we can't add overrides, we can fix types and create another issue to fix test linting errors after if we want to land it quicker.

2021-03-04 09:09 UTC, fox1t requested changes

2021-03-04 09:09 UTC, fox1t commented on test/types/plugin.test-d.ts
> +expectAssignable<FastifyInstance>(fastify().register(async function (instance, opts): Promise<void> { return await Promise.resolve() }))
```suggestion
expectAssignable<FastifyInstance>(fastify().register(async function (instance, opts): Promise<void> { return Promise.resolve() }))
```

2021-03-04 09:21 UTC, mcollina commented
there is no need for quick :)

2021-03-04 11:54 UTC, zekth commented
I made some disables in files because `ts-standard` does not support the overrides, we use those for the tests.
Also i need help for the errors `void is only valid as a return type or generic type variable  @typescript-eslint/no-invalid-void-type` on the types. If someone got a lead on this.

2021-03-05 10:46 UTC, zekth commented
@Ethan-Arrowood we are stuck on the last test with @fox1t , if you have a clue feel free to help

2021-03-09 04:30 UTC, Ethan-Arrowood commented on test/types/plugin.test-d.ts
> +// async function testAsync (): Promise<void> {
can this be removed if unused?

2021-03-09 04:42 UTC, Ethan-Arrowood commented
huh im stumped. does it run locally by any chance? its strange that its the `put` one thats failing and not the others

2021-03-09 09:23 UTC, zekth commented
> huh im stumped. does it run locally by any chance? its strange that its the `put` one thats failing and not the others

unfortunately no

2021-03-13 08:37 UTC, zekth commented
@fastify/typescript any idea how we can fix and land this?

2021-03-15 20:58 UTC, Ethan-Arrowood commented
> @fastify/typescript any idea how we can fix and land this?

I think if someone has the capacity, simplify this issue to a reproducible typescript playground link and we can go from there. I can forward it along to the TS folks if we think something is actually wrong

2021-03-17 21:12 UTC, zekth commented
@fox1t i did a rebase and one more issue showed up :(

2021-08-03 09:38 UTC, closed without merging