Tap15 support
fastify/fastify pull request #2986
Opened 2021-04-06 15:53 UTC by makuzaverite

Migrate tests to tap15.0.1

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-04-06 17:20 UTC, Eomm commented on .taprc
>  flow: false
adding 

```
check-coverage: false
```

should fix the pipeline

2021-04-06 17:33 UTC, makuzaverite commented on .taprc
>  flow: false
it didn't

2021-04-06 18:41 UTC, climba03003 commented
I think there are something wrong with your commit history.
Some of the test case is not updated in your branch.

For example:
https://github.com/fastify/fastify/blob/main/test/async-await.test.js#L425
https://github.com/makuzaverite/fastify/blob/tap15Support/test/async-await.test.js#L425

I think you should reset the commit history to match the upstream before starting a new PR.

2021-04-06 18:54 UTC, climba03003 requested changes

2021-04-06 18:54 UTC, climba03003 commented on test/async-await.test.js
> +    t.eqaul(res.statusCode, 401)
Typo
```suggestion
    t.equal(res.statusCode, 401)
```

2021-04-06 18:54 UTC, climba03003 commented on test/async-await.test.js
> +    t.eqaul(res.statusCode, 401)
Typo
```suggestion
    t.equal(res.statusCode, 401)
```

2021-04-06 18:54 UTC, climba03003 commented on test/async-await.test.js
> +    t.eqaul(res.statusCode, 200)
Typo
```suggestion
    t.equal(res.statusCode, 200)
```

2021-04-06 20:37 UTC, makuzaverite commented
Thanks @climba03003 had a wrong select and replace inside my vscode

2021-04-07 04:10 UTC, climba03003 requested changes
Can you double check it is not missing any of the wrong replacement? I may miss some of them when I glance through this big changes.

2021-04-07 04:10 UTC, climba03003 commented on test/async-await.test.js
> +test('server logs an error if reply.send is called and a value equal returned via async/await', t => {
Wrong replacement
```suggestion
test('server logs an error if reply.send is called and a value is returned via async/await', t => {
```

2021-04-07 06:55 UTC, mcollina commented on docs/Hooks.md
> +    assert.equal(this.foo, undefined)
This was correct, please restore

2021-04-07 06:55 UTC, mcollina commented on docs/Hooks.md
> +    assert.equal(this.foo, 'bar')
This was correct, please restore

2021-04-07 06:55 UTC, mcollina commented on docs/Hooks.md
> +  assert.equal(this.foo, undefined)
This was correct, please restore

2021-04-07 06:55 UTC, mcollina commented on docs/Hooks.md
> +    assert.equal(this.foo, 'bar')
This was correct, please restore

2021-04-08 13:14 UTC, zekth commented on test/async-await.test.js
> +test('inject async await - when the server equal up', async t => {
@makuzaverite still this to fix

2021-04-08 13:19 UTC, mcollina approved these changes
lgtm, thanks for the gargantuan effort!

2021-04-08 14:39 UTC, zekth approved these changes
lgtm huge work

2021-04-08 15:59 UTC, merged