docs(examples): use console.log to log address
fastify/fastify pull request #3048
Opened 2021-04-29 19:46 UTC by RafaelGSS

The other examples are using `console﻿` to print the startup as well.

2021-04-29 19:51 UTC, climba03003 commented
I advise to do the reverse way, change all the `console.log` to `fastify.log.info`.

2021-04-29 19:53 UTC, RafaelGSS commented
> I advise to do the reverse way, change all the `console.log` to `fastify.log.info`.

In the startup it would be printed twice since we already loging on `listen` here: https://github.com/fastify/fastify/blob/main/lib/server.js#L119

2021-04-29 20:00 UTC, climba03003 commented
> 
> 
> > I advise to do the reverse way, change all the `console.log` to `fastify.log.info`.
> 
> In the startup it would be printed twice since we already loging on `listen` here: https://github.com/fastify/fastify/blob/main/lib/server.js#L119

It is the same for `console.log` if we enable the logger. I do not see any conflict if the user want to explicitly log it again when startup. 

The only problem is `simple.js` disable the logger in the top and I support it should be using `console.log`.

2021-04-29 20:17 UTC, RafaelGSS commented
> It is the same for console.log if we enable the logger. I do not see any conflict if the user want to explicitly log it again when startup.

I don't see either, but as you said, it's explicitly declared as `false` on top.

2021-04-29 21:59 UTC, mcollina commented
We should remove all those log lines in the examples, it's already done by fastify.

2021-04-30 12:11 UTC, jsumners commented on examples/simple.js
> +  console.info(`server listening on ${address}`)
```suggestion
```

2021-04-30 13:20 UTC, RafaelGSS commented
Updated all the examples adding `logger: true` and removing `console.log` on `listen`.

2021-04-30 13:34 UTC, mcollina commented
`example/simple` has logging disabled because we use it for benchmarks. Maybe we should divide these use cases and have a dedicated file for benchmarks with logging off.

2021-04-30 13:36 UTC, jsumners commented
> `example/simple` has logging disabled because we use it for benchmarks. Maybe we should divide these use cases and have a dedicated file for benchmarks with logging off.

Yes.

2021-04-30 13:36 UTC, RafaelGSS commented
> `example/simple` has logging disabled because we use it for benchmarks. Maybe we should divide these use cases and have a dedicated file for benchmarks with logging off.

Agree. I'll revert this file, but I'll create a new PR for this proposal.

2021-04-30 13:40 UTC, RafaelGSS commented
> `example/simple` has logging disabled because we use it for benchmarks.

Actually, can you send me where we use this? I thought that is on `fastify/benchmarks`, but I don't found it there.

2021-04-30 14:00 UTC, mcollina commented
https://github.com/fastify/fastify/blob/main/package.json#L10

2021-04-30 20:56 UTC, RafaelGSS commented
This PR is open to review. The new file for benchmark would be in a new PR.

2021-05-01 08:02 UTC, zekth approved these changes
lgtm. Need to create a proper benchmark file indeed.

2021-05-01 09:44 UTC, mcollina commented
> This PR is open to review. The new file for benchmark would be in a new PR.

We are not in agreement. This PR is breaking the benchmarks, so it should be fixed here.

2021-05-01 09:44 UTC, mcollina requested changes

2021-05-01 09:44 UTC, mcollina commented on examples/hooks-benchmark-async-await.js
> +const fastify = require('../fastify')({ logger: true })
I would not enable the logger here, it seems it can be used for benchmarking.

2021-05-01 09:44 UTC, mcollina commented on examples/hooks-benchmark.js
> +const fastify = require('../fastify')({ logger: true })
I would not enable the logger here, it seems it can be used for benchmarking.

2021-05-02 21:07 UTC, RafaelGSS commented
Added the benchmark files to `examples/benchmark/*`. I've moved `hooks-benchmark-async-await.js` and `hooks-benchmark.js` to that folder as well.

2021-05-02 21:42 UTC, mcollina approved these changes
lgtm

2021-05-02 21:46 UTC, merged