add TOC
fastify/fastify pull request #3055
Opened 2021-05-05 12:09 UTC by namerhila

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

This PR fix this issue https://github.com/fastify/fastify/issues/3010

2021-05-05 12:13 UTC, jsumners requested changes

2021-05-05 12:13 UTC, jsumners commented on package.json
> +    "markdown-it": "^12.0.6",
Why have you added this new dependency?

2021-05-05 12:13 UTC, jsumners commented on README.md
> + - [License](https://github.com/fastify/fastify#license)
These should be relative links.

2021-05-05 12:19 UTC, RafaelGSS requested changes
The new feature from GitHub doesn't solve it? 
![image](https://user-images.githubusercontent.com/26234614/117139752-fc966300-ad82-11eb-803e-8cf027fa620a.png)

2021-05-05 12:21 UTC, RafaelGSS commented
> The new feature from GitHub doesn't solve it?

I've just seen that we parse the table of contents on our website.

2021-05-15 06:28 UTC, Eomm reviewed
> This PR fix this issue #3010

Nope, that issue refers to this page:

![image](https://user-images.githubusercontent.com/11404065/118350519-7551a800-b557-11eb-8033-ba0f6a9026f9.png)

2021-05-15 08:51 UTC, mcollina approved these changes
lgtm with @jsumners changes

2022-01-26 16:58 UTC, closed without merging