Clarification for "Simplify reply sent monitoring (#3072)"
fastify/fastify pull request #3132
Opened 2021-06-13 08:53 UTC by sergiz

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

After studying the reasoning behind https://github.com/fastify/fastify/issues/3107, I found out that the reply.send() will behave like synchronous method most of the time, but in rare situations it will not fully complete before async function is resolved. Therefore, not awaiting the reply will introduce a race condition. This is already the case in current version, but since marking reply as sent is done manually, it was very hard to notice this problem. Now that the reply is marked as sent only after response is actually sent, such situation can occur more frequently.

I updated the docs to warn users to await (or return) for reply in their async handlers when using reply.send() manually. I also updated the tests, so they cannot fail due to this race condition.

The example that could trigger such situation:
```js
  fastify.addHook('onSend', async (request, reply, payload) => {
    if (payload === 'OK') {
      await new Promise((resolve) => {
        setImmediate(resolve)
      })
    }

    return payload
  })

  fastify.get('/', async (req, reply) => {
    reply.send('OK')
  })
```
The handler will resolve and send reply before reply.send() called from within handler has finished its operation.

2021-06-13 10:48 UTC, mcollina requested changes
Why all the test changes? I don't think we should change them.

2021-06-13 12:29 UTC, sergiz commented
Not waiting for reply.send() in async handler to finish introduces a race condition if there's async hook added which runs before reply is sent (for example onSend as shown in the example). They are not failing now, but might start in the future if something is changed and it won't be clear right away why they are suddenly failing.

2021-06-13 12:31 UTC, zekth commented
> Why all the test changes? I don't think we should change them.

Wouldn't those break with the fastify 4 implementation ? (The one which got reverted in 3.17)

2021-06-13 12:37 UTC, sergiz commented
The tests do not fail because of how the is currently structured, but a little change in the future can make them fail

> > Why all the test changes? I don't think we should change them.
> 
> Wouldn't those break with the fastify 4 implementation ? (The one which got reverted in 3.17)

They do not break because of the way the code is structured at the moment. However, a possible change in the future which would change the order of promise resolution would make them fail. Not awaiting for reply.send() in async handler is already wrong in the current version, but there is no realistic way to actually experience a problem because of it.

2021-06-13 22:10 UTC, mcollina approved these changes
lgtm

2021-06-13 22:11 UTC, mcollina commented
thanks, ok for me!

2021-06-14 07:50 UTC, Eomm approved these changes

2021-06-14 20:22 UTC, merged