docs: clarify on `request.body` content and usage
fastify/fastify pull request #3436
Opened 2021-11-12 15:04 UTC by Fdawgs

Closes #3389

#### Checklist

- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-11-12 18:30 UTC, jsumners approved these changes
Looks good to me.

2021-11-12 19:20 UTC, RafaelGSS approved these changes
LGTM.

2021-11-13 05:18 UTC, climba03003 requested changes
Missing a closing bracket

2021-11-13 05:18 UTC, climba03003 commented on docs/Getting-Started.md
> +const opts = {
```suggestion
const opts = {}
```

2021-11-13 07:21 UTC, climba03003 approved these changes

2021-11-13 07:23 UTC, mcollina approved these changes
lgtm

2021-11-13 07:23 UTC, merged