fix types: update validatorCompiler options
fastify/fastify pull request #3462
Opened 2021-11-19 02:05 UTC by joshuaavalon

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Related issues: #3457

2021-11-19 07:47 UTC, Eomm commented
Would you mind to add a test [here](https://github.com/fastify/fastify/blob/master/test/types/index.ts)?

2021-11-20 06:52 UTC, joshuaavalon commented
> Would you mind to add a test [here](https://github.com/fastify/fastify/blob/master/test/types/index.ts)?

Where are you referring to? I got 404 with your link, Do you mean add a test to `test/types`?

2021-11-20 07:44 UTC, Eomm commented
Yeah, fixed the link https://github.com/fastify/fastify/tree/main/test/types

2021-11-20 18:06 UTC, climba03003 requested changes

2021-11-20 18:06 UTC, climba03003 commented on fastify.d.ts
> +  ajv?: Ajv,
Let's do the same as `serializerOpts`.

2021-11-20 18:06 UTC, climba03003 commented on fastify.d.ts
> +  Ajv = FastifyAjvOptions
I do not think it is good to add one more parameter here.

2021-11-21 16:50 UTC, joshuaavalon commented
I removed generics but I kept `FastifyAjvOptions`. By removing generics, users cannot pass the custom options, but keeping `FastifyAjvOptions` at least allows users to extends the interface in their code.

2022-02-03 08:23 UTC, mcollina commented
@fastify/typescript could you take a look?

2022-04-27 23:29 UTC, closed without merging