Add prototype poisoning doc
fastify/fastify pull request #3609
Opened 2022-01-10 23:12 UTC by jsumners

Resolves issue #3003.

cc: @hueniverse

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-01-11 01:41 UTC, RafaelGSS approved these changes
LGTM.

2022-01-11 03:15 UTC, luisorbaiceta requested changes

2022-01-11 03:15 UTC, luisorbaiceta commented on docs/Guides/Prototype-Poisoning.md
> +[qs ](https://www.npmjs.com/package/qs) —  was not vulnerable (it is not!).
There is an extra space that will get underlined on website links

2022-01-11 03:48 UTC, jsumners commented on docs/Guides/Prototype-Poisoning.md
> +[qs ](https://www.npmjs.com/package/qs) —  was not vulnerable (it is not!).
```suggestion
[qs](https://www.npmjs.com/package/qs) —  was not vulnerable (it is not!).
```

2022-01-11 04:51 UTC, luisorbaiceta approved these changes
lgtm!

2022-01-11 05:31 UTC, climba03003 approved these changes
LGTM.

2022-01-11 06:29 UTC, hueniverse commented
I think you should remove all the non-technical relevant stuff and instead of the strong attribution, simply replace it with "Based on the article ... by Eran Hammer". I'm giving you full permission to use this text as you find useful. Don't be shy to change it.

2022-01-11 07:05 UTC, mcollina approved these changes
lgtm

2022-01-11 13:29 UTC, jsumners commented
> I think you should remove all the non-technical relevant stuff and instead of the strong attribution, simply replace it with "Based on the article ... by Eran Hammer". I'm giving you full permission to use this text as you find useful. Don't be shy to change it.

Thank you. I appreciate the suggestion. Right now, I do not have the time to massage the language like that. I have created a new issue to address it in the future.

2022-01-11 13:29 UTC, merged

2022-01-19 18:24 UTC, rluvaton commented
Just wanted to say it was delightful to read, thank you 😀