Update Routes.md
fastify/fastify pull request #3835
Opened 2022-04-13 22:40 UTC by PazzaVlad

I think it's not quite obvious that you have to escape slashes in regexp. So maybe it's worth mentioning that in the description.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-04-14 18:23 UTC, mcollina approved these changes
lgtm

2022-04-27 13:16 UTC, Fdawgs requested changes

2022-04-27 13:16 UTC, Fdawgs commented on docs/Reference/Routes.md
> +Regular expression routes are supported as well, but beware that you have to escape slashes. Also notice, that RegExp are very expensive in term of performance!
```suggestion
Regular expression routes are supported as well, but be aware that you have to escape slashes. Take note that RegExp is also very expensive in terms of performance!
```

2022-04-27 20:47 UTC, mcollina approved these changes
lgtm

2022-04-27 20:47 UTC, merged