Child log level in bindings is deprecated
fastify/fastify pull request #3896
Opened 2022-05-11 11:13 UTC by orov-io

Update Logger types to add options to the child function.

ChildLoggerOptions and redactOptions interface was copied from the pino library types.

logger test runs.

2022-05-11 11:18 UTC, climba03003 requested changes
Can you add a test in https://github.com/fastify/fastify/blob/main/test/types/logger.test-d.ts
It can ensure the type is working properly

2022-05-11 11:35 UTC, orov-io commented
like this?

```typescript
const loggerChild = fastify({
  logger: true
}).log.child({}, {level: 'trace'})

expectType<FastifyLoggerInstance>(loggerChild)
```

I'm not pretty sure about how to test it in another way

2022-05-11 11:39 UTC, climba03003 commented
> 



> like this?
> 
> ```ts
> const loggerChild = fastify({
>   logger: true
> }).log.child({}, {level: 'trace'})
> 
> expectType<FastifyLoggerInstance>(loggerChild)
> ```
> 
> I'm not pretty sure about how to test it in another way

Mostly, correct.

```js
const childParent = fastify().log
// we test different option variant here
expectType<FastifyLoggerInstance>(childParent.child({}, { level: ... }))
expectType<FastifyLoggerInstance>(childParent.child({}, { redact: ... }))
expectType<FastifyLoggerInstance>(childParent.child({}, { serializers: ... }))
expectType<FastifyLoggerInstance>(childParent.child({}, { level: ..., redact: ..., serializers: ... }))
```

2022-05-11 12:06 UTC, orov-io commented
ok, I need to return to my work for others stuffs, I'll push the test ASAP :)

2022-05-30 09:23 UTC, kibertoad commented
@orov-io ping?

2022-06-01 15:02 UTC, merged