docs(Reference/Logging): update suggested pino-pretty configuration
fastify/fastify pull request #3933
Opened 2022-05-24 23:19 UTC by mweberxyz

Passing prettyPrint: true/false/{} at the top level to pino configuration is deprecated.

Update docs to configure pino-pretty as a transport when in development, as suggested here — https://github.com/pinojs/pino-pretty#programmatic-integration

#### Checklist

- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-05-24 23:34 UTC, mweberxyz commented
Originally came across this while updating deps on a project to v4.0.0 release candidate and mentioned in v4 tracking issue https://github.com/fastify/fastify/issues/3482

2022-05-25 05:21 UTC, climba03003 requested changes
https://github.com/mweberxyz/fastify/blob/427deed49a91a3cf13d278b8d6c1fc95f76b8335/docs/Reference/Logging.md?plain=1#L125

Line 125 also need to change.

2022-05-25 14:55 UTC, mweberxyz commented
Took care of the the additional reference in Logging.md, and found another in Guides/Testing.md

2022-05-25 14:57 UTC, climba03003 approved these changes
LGTM.

2022-05-25 14:59 UTC, merged