fix: fix outdated type definition in ValidationResult interface (fastify#4045)
fastify/fastify pull request #4062
Opened 2022-06-21 10:54 UTC by micheleriva

Hi there,
this commit fixes fastify#4045. There was an outdated type reference inside of fastify.d.ts that caused a type mismatch with the AJV library.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-06-21 13:27 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test? We use `tsd` to test our types

2022-06-21 13:28 UTC, RafaelGSS approved these changes

2022-06-23 08:23 UTC, closed without merging

2022-06-23 08:27 UTC, mcollina commented
why did you close the PR?

2022-06-23 10:53 UTC, mcollina commented
which one?

2022-06-23 12:14 UTC, RafaelGSS commented
> which one?

https://github.com/fastify/fastify/pull/4070