Readd typed decorators
fastify/fastify pull request #4111
Opened 2022-07-04 11:50 UTC by wyozi

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-07-04 16:55 UTC, mcollina approved these changes
lgtm

2022-07-05 10:56 UTC, climba03003 requested changes
~~I think it is a breaking change since the order of generic is changed~~

I see the comment on the issue.

2022-07-05 10:59 UTC, climba03003 approved these changes

2022-07-05 12:08 UTC, mcollina commented
@fastify/typescript please chime in

2022-07-09 08:30 UTC, merged