Update TypeScript.md
fastify/fastify pull request #4126
Opened 2022-07-09 15:19 UTC by mikicho

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-07-09 15:32 UTC, climba03003 reviewed
I think we need to elaborate more on this area.

TypeScript can only identify the types that are direct `imported` in code which means that you can use `require` inline with `import` on top.

For example,
```js
import 'plugin' // here will trigger the type augmentation.

fastify.register(require('plugin'))

import plugin from 'plugin' //  here will trigger the type augmentation.
fastify.register(plugin)
```
Or even explicit config on `tsconfig`
```json
{
  "types": ["plugin"] // we force TypeScript to import the types
}
```

2022-07-09 17:45 UTC, mcollina approved these changes
lgtm

2022-07-09 18:58 UTC, mikicho commented
@climba03003 WDYT?

2022-07-09 19:11 UTC, climba03003 approved these changes
LGTM.

Except the line need to be formatted and break in length 80.

2022-07-09 20:05 UTC, RafaelGSS approved these changes

2022-07-10 08:19 UTC, Fdawgs requested changes

2022-07-10 08:19 UTC, Fdawgs commented on docs/Reference/TypeScript.md
> +Note that using `require` won't load the type definitions properly and may
```suggestion
Note that using `require` will not load the type definitions properly and may
```

Reference docs are formal, so contractions shouldn't be used.

2022-07-10 08:19 UTC, Fdawgs commented on docs/Reference/TypeScript.md
> +which means that you can use require inline with import on top, for example:
```suggestion
TypeScript can only identify the types that are directly imported into code,
which means that you can use require inline with import on top. For example:
```

2022-07-10 08:19 UTC, Fdawgs commented on docs/Reference/TypeScript.md
> +```json
```suggestion
```jsonc
```

2022-07-10 16:34 UTC, mikicho commented
Thanks! @Fdawgs

2022-07-10 18:47 UTC, Fdawgs approved these changes

2022-07-11 07:39 UTC, mcollina approved these changes
lgtm

2022-07-11 07:39 UTC, merged