docs: onRoute hooks in plugins
fastify/fastify pull request #4285
Opened 2022-09-16 15:51 UTC by philsch

Add an example to the plugin guide how the onRoute hook can be used #4282 .

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-09-16 18:44 UTC, mcollina approved these changes
lgtm

2022-09-18 08:51 UTC, Fdawgs requested changes
Will review properly when back at computer.

2022-09-19 16:05 UTC, anonrig approved these changes

2022-09-20 06:53 UTC, Fdawgs commented on docs/Guides/Plugins-Guide.md
> +a new route gets registered, you can read and modify the route options, for example
```suggestion
a new route is registered, you can read and modify the route options. For example,
```

2022-09-20 07:37 UTC, Fdawgs approved these changes

2022-09-20 09:29 UTC, Uzlopak approved these changes

2022-09-20 09:30 UTC, Eomm approved these changes

2022-09-20 09:30 UTC, merged