docs: replace heply -> beliven due to rebranding
fastify/fastify pull request #4334
Opened 2022-10-13 08:53 UTC by zuck

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-10-13 09:24 UTC, delvedor requested changes
Thanks for the pr. Can you fix the linter issues?

2022-10-13 12:39 UTC, mcollina approved these changes
lgtm

2022-10-15 09:26 UTC, Eomm approved these changes

2022-10-15 20:35 UTC, RafaelGSS approved these changes

2022-10-16 08:16 UTC, Fdawgs approved these changes

2022-10-16 08:17 UTC, merged