Add fastify-postgres-dot-js plugin to ecosystem docs.
fastify/fastify pull request #4514
Opened 2023-01-14 14:20 UTC by kylerush

Add [`fastify-postgres-dot-js`]() plugin to ecosystem docs.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-01-14 20:25 UTC, mcollina requested changes
Can you put your plugin in alphabetical order?

2023-01-15 15:27 UTC, jsumners approved these changes

2023-01-15 15:28 UTC, Uzlopak approved these changes

2023-01-15 18:46 UTC, mcollina approved these changes
lgtm

2023-01-15 18:46 UTC, merged