docs(Ecosystem): add metcoder95/fastify-ip
fastify/fastify pull request #4517
Opened 2023-01-16 15:33 UTC by metcoder95

As a result of #4499, I came up with a small plugin for customizing the inferring for the request-id given a set of predefined Request headers + the custom ones that can be added while using the plugin.

- [fastify-ip](https://github.com/metcoder95/fastify-ip)

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-01-16 16:57 UTC, Eomm commented on docs/Guides/Ecosystem.md
> +- [`fastify-ip`](https://github.com/metcoder95/fastify-ip) A plugin for Fastify that allows you to infer a request ID by a given set of custom Request headers.
```suggestion
- [`fastify-ip`](https://github.com/metcoder95/fastify-ip) A plugin for Fastify
  that allows you to infer a request ID by a given set of custom Request headers.
```

2023-01-17 13:10 UTC, Fdawgs requested changes
CI failing due to plugin not being added in alphabetical order.

2023-01-17 23:30 UTC, jsumners approved these changes

2023-01-18 05:25 UTC, Fdawgs approved these changes

2023-01-18 05:25 UTC, merged