Install pnpm version 7 for CI to support Node.js 14
fastify/fastify pull request #4645
Opened 2023-03-29 04:22 UTC by Yvad60

#### Description
PR fixes #4643 by installing pnpm version 7 which supports Node.js 14, using [setup pnpm action](https://github.com/marketplace/actions/setup-pnpm)

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-03-29 05:50 UTC, Eomm approved these changes
we run this pipeline on push into `main`, but LGTM https://github.com/pnpm/action-setup

2023-03-29 06:08 UTC, climba03003 requested changes

2023-03-29 06:08 UTC, climba03003 commented on .github/workflows/package-manager-ci.yml
> +          version 7
```suggestion
          version: 7
```

2023-03-29 06:59 UTC, Yvad60 commented on .github/workflows/package-manager-ci.yml
> +          version 7
Ahh! thanks for the catch 👍

2023-03-29 14:52 UTC, jsumners commented on .github/workflows/package-manager-ci.yml
> +          version: 7
```suggestion
        with:
          # pnpm@8 does not support Node.js 14
          version: 7
```

2023-03-29 16:50 UTC, Yvad60 commented on .github/workflows/package-manager-ci.yml
> +          version: 7
Comment added

2023-03-30 05:39 UTC, climba03003 requested changes
From the log, it still using `pnpm@8`.
Please also change

https://github.com/fastify/fastify/blob/bf1214879d9ad7baecba0b9af7d1e9ddbf41044e/.github/workflows/integration.yml#L34-L36

2023-03-30 06:56 UTC, mcollina approved these changes
lgtm

2023-03-30 09:10 UTC, merged