docs: add optional URL param to upgrade guide and route docs (#4637)
fastify/fastify pull request #4680
Opened 2023-04-14 20:04 UTC by mateus4k

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-04-17 07:19 UTC, Fdawgs commented
Thanks for the PR, can you please resolve the linting CI failing?

2023-04-17 18:06 UTC, mateus4k commented
Oh, I didn't see that, @Fdawgs. It's fixed now!

2023-04-18 07:35 UTC, Fdawgs requested changes

2023-04-18 13:52 UTC, Fdawgs approved these changes

2023-04-19 07:59 UTC, merged