Add fastify-type-provider-effect-schema link to Ecosystem.md
fastify/fastify pull request #4683
Opened 2023-04-16 09:47 UTC by NexZhu

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-04-16 20:37 UTC, metcoder95 requested changes

2023-04-16 20:37 UTC, metcoder95 commented on docs/Guides/Ecosystem.md
> +- [`fastify-type-provider-effect-schema`](https://github.com/daotl/fastify-type-provider-effect-schema)
It is not alphabetically positioned

2023-04-19 06:34 UTC, Fdawgs approved these changes

2023-04-19 07:10 UTC, mcollina approved these changes
lgtm

2023-04-19 07:47 UTC, metcoder95 approved these changes

2023-04-19 07:57 UTC, merged