Add support for lowercase HTTP methods in route() method
fastify/fastify pull request #4747
Opened 2023-05-12 15:57 UTC by ashikkabeer

#### Checklist

- [ x] run `npm run test` and `npm run benchmark`
- [x ] tests and/or benchmarks are included
- [ x] documentation is changed or added
- [x ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-05-12 16:00 UTC, jsumners requested changes
Please add unit tests to cover this.

2023-05-13 03:30 UTC, ashikkabeer commented
@jsumners I don't really know how to write unit tests. Can you help me with some information on that? I saw there are many frameworks for that. What framwork should i use ?

2023-05-13 04:49 UTC, Uzlopak commented
See /test/route.js

You basically have to do:

```
test('route - lowercase method', t => {
    t.plan(3)
      fastify.route({
        method: 'get',
        url: '/lowercase',
        handler: function (req, reply) {
          reply.send({ hello: 'world' })
        }
      })
      sget({
        method: 'GET',
        url: 'http://localhost:' + fastify.server.address().port + '/lowercase'
      }, (err, response, body) => {
        t.error(err)
        t.equal(response.statusCode, 200)
        t.same(JSON.parse(body), { hello: 'world' })
      })
  })
```

I didnt test it, wrote it on my mobile. But you should get the gist...

2023-05-13 08:28 UTC, Eomm commented on fastify.js
> +            options.method = options.method.toUpperCase();
Note that this `method` could be an array, so we should support `method: ['get', 'POST']` too

2023-05-14 05:40 UTC, closed without merging

2023-05-14 07:10 UTC, ashikkabeer commented
@Uzlopak I got this error  FAIL ​ test/route.test.js 1 failed of 187 7s
 ✖ Cannot read property 'port' of null

2023-05-14 09:58 UTC, Uzlopak commented
@ashikkabeer 

Sry, i saw now, that you commented. I thought, that you closed out of frustration. 

I opened #4750 as a follow up PR. It was imho a little bit more complicated to implement it properly.

2023-05-14 10:58 UTC, ashikkabeer commented
I wasn't frustrated or anything. I closed it accidentally. I'm starting to do OpenSource contributions and this is my first code contribution attempt. :)