Add missing trailer method definitions
fastify/fastify pull request #4759
Opened 2023-05-17 04:04 UTC by atesgoral

`reply.d.ts` is missing the `trailer`, `hasTrailer` and `removeTrailer` method definitions.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-05-17 09:00 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test? We use tsd for types.

2023-05-17 13:50 UTC, mcollina approved these changes
lgtm

2023-05-17 14:57 UTC, climba03003 commented on types/reply.d.ts
> +  ) => FastifyReply<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider>;
```suggestion
  trailer: (
    key: string,
    fn: ((reply: FastifyReply<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider>, payload: string | Buffer | null) => Promise<string>) | ((reply: FastifyReply<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider>, payload: string | Buffer | null, done: (err: Error | null, value?: string) => void) => void)
  ) => FastifyReply<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider>;
```

2023-05-17 14:57 UTC, climba03003 commented on test/types/reply.test-d.ts
> +  expectType<(key: string, fn: (() => string) | ((reply: FastifyReply, payload: string | Buffer | null) => Promise<string>) | ((reply: FastifyReply, payload: string | Buffer | null, done: (err: Error
```suggestion
  expectType<(key: string, fn: ((reply: FastifyReply, payload: string | Buffer | null) => Promise<string>) | ((reply: FastifyReply, payload: string | Buffer | null, done: (err: Error | null, value?: string) => void) => void)) => FastifyReply>(reply.trailer)
```

2023-05-17 17:01 UTC, atesgoral commented
@climba03003 Makes sense! I had been on the fence about it.

2023-05-18 11:48 UTC, Eomm approved these changes

2023-05-18 11:48 UTC, merged