First Commit
fastify/fastify pull request #4849
Opened 2023-06-23 21:25 UTC by Ekott2006

This PR adds documentation for testing a plugin in Fastify (https://github.com/fastify/fastify/issues/4687)
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-06-25 09:30 UTC, Fdawgs requested changes

2023-06-25 09:30 UTC, Fdawgs commented on docs/Guides/Testing.md
> +**Table of contents**
Not needed as the site will generate a ToC from the markdown headers: https://fastify.dev/docs/latest/Guides/Testing

2023-06-25 09:30 UTC, Fdawgs commented on docs/Guides/Testing.md
> +To use ESM (`import` statements)
All other examples in our documentation use CommonJS, please do the same for this example.

2023-06-30 12:50 UTC, mcollina approved these changes
lgtm

2023-06-30 13:53 UTC, Fdawgs approved these changes

2023-07-01 06:47 UTC, merged