fix: ReplyTypeConstrainer array type inference
fastify/fastify pull request #4885
Opened 2023-07-07 10:26 UTC by pedroescumalha

Closes #4883

As @aadito123 mentioned on the issue, there's a pitfall here: if someone wants the Reply type to be an object with keys as http codes like `{ 401: unknown, 409: unknown }`, the inference of the return type will be `unknown`.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-07-08 06:36 UTC, mcollina approved these changes
lgtm

2023-07-08 10:59 UTC, pedroescumalha commented
Hey @mcollina could you take a look again? Found an issue with the previous type definition:

```
import fastify from '../fastify'

const server = fastify()

type TestReply = {
    200: string;
    10000: Date;
};

server.get<{ Reply: TestReply }>(
  '/ping',
  { schema: {} },
  async (request, reply) => {
    reply.code(10000).send() // type is inferred to a Date
  }
)
```
The type has an invalid status code, and `code().send()` was still inferring to `TestResponse[code]`.
In this new implementation we make sure that if the reply object consists of only valid http status codes we infer to `TestReply[code]`, otherwise it's infered to `TestReply`.

2023-07-08 11:34 UTC, mcollina approved these changes
lgtm

2023-07-08 19:03 UTC, Uzlopak commented
I have to be honest:
This PR is quiete complicated. The typings test imply that the underlying issue is fixed. But does it have other effects? I dont know.
Unfortunately the typings tests are actually not good enough, as we actually needed to determine what the first Parameter of .send exactly is. We currently implicitly check that. This could mean that .send() parameter is implicitly any or so, and that is why maybe other cases, which were before stricter, are now less strict and thus dont throw error in tsd. 

I personally dont know, if this PR means regressions in other cases.

2023-07-09 14:05 UTC, mcollina commented
@climba03003 @fox1t wdyt?

2023-07-10 16:47 UTC, climba03003 requested changes

2023-07-10 16:47 UTC, climba03003 commented on test/types/reply.test-d.ts
> +    '1xx': number,
`1xx` should be a correct http code.
It is a fallback for all status code starting with `1`

2023-07-11 07:56 UTC, metcoder95 commented on types/reply.d.ts
> +    Code extends keyof RouteGenericReply ? Required<RouteGenericReply[Code]> :
Yes - https://www.typescriptlang.org/docs/handbook/utility-types.html#requiredtype

2023-07-11 09:08 UTC, pedroescumalha commented on types/reply.d.ts
> +    Code extends keyof RouteGenericReply ? Required<RouteGenericReply[Code]> :
True, it's not needed at all. Just removed it.

2023-07-26 08:29 UTC, merged