Update Ecosystem.md
fastify/fastify pull request #4895
Opened 2023-07-10 17:18 UTC by RjManhas

added mediumFastifyPlugin to community plugins

2023-07-10 18:00 UTC, climba03003 requested changes

2023-07-10 18:00 UTC, climba03003 commented on docs/Guides/Ecosystem.md
> +- [`mediumFastifyPlugin`](https://github.com/devoplx/mediumFastifyPlugin) A simple plugin for using medium.com api.
Can you place in alphabetically order?

2023-07-13 06:30 UTC, Uzlopak commented
I dont know how to say that diplomatically.

Usually if I see a new plugin for the ecosystem, I check the npm package content to check if there is some malware to avoid promoting malicious packages on the fastify webpage. But I am kind of disappointed that this package is basically overbloated and not at all optimized for performance. 

@mcollina 
I think we should actually think about some quality policies for the plugins we are promoting on our page.

2023-07-13 07:54 UTC, mcollina commented
There are a few things that are missing:

* API documentation
* remove unneeded dependencies (fastify, tap, tsup, etc can all go into devdeps)
* move away from a [singleton](https://github.com/devoplx/mediumFastifyPlugin/blob/07d50a177fc9142aeefb9750e1934a2339459832/src/services/api.ts#L139) and move initialization inside the [plugin constructor](https://github.com/devoplx/mediumFastifyPlugin/blob/07d50a177fc9142aeefb9750e1934a2339459832/src/index.ts#L19)

2023-08-21 13:24 UTC, Uzlopak commented
Closing due to inactivity

2023-08-21 13:25 UTC, closed without merging