ERR_REP_ALREADY_SENT explicitate that a route is missing "return reply"
fastify/fastify pull request #4921
Opened 2023-07-21 10:26 UTC by mcollina

Fixes #4911

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-07-21 11:55 UTC, jsumners commented on bug.js
Should this file be located in the test filesystem, e.g `test/fixtures/`? Maybe name it `issue-4911.js`?

2023-07-21 15:28 UTC, metcoder95 commented on lib/reply.js
> +    this.log.warn({ err: new FST_ERR_REP_ALREADY_SENT(this.request.url) })
Should we include the `method` here to distinguish between handlers?
Asking as is possible the same route is bounded to different methods

2023-07-21 19:04 UTC, Uzlopak requested changes
The title is not right i think. 

"fix: ERR_REP_ALREADY_SENT explicitate that a handler is missing "return reply""

Is this about those async handlers? Than it should be 
"fix: ERR_REP_ALREADY_SENT explicitate that an async handler is missing "return reply""

2023-07-21 19:07 UTC, Fdawgs requested changes

2023-07-21 19:07 UTC, Fdawgs commented on lib/reply.js
> +      reply.log.warn(`The reply already sent, did you forget to "return reply" in the "${reply.request.raw.url}" route?`)
```suggestion
      reply.log.warn(`Reply was already sent, did you forget to "return reply" in the "${reply.request.raw.url}" route?`)
```
Lines up with the change in `lib.errors.js`

2023-07-24 09:27 UTC, Uzlopak approved these changes
LGTM

2023-07-24 12:12 UTC, jsumners approved these changes

2023-07-24 12:24 UTC, Fdawgs approved these changes

2023-07-24 12:33 UTC, Eomm approved these changes

2023-07-24 12:34 UTC, merged