docs: Update Lifecycle.md
fastify/fastify pull request #4932
Opened 2023-07-24 19:30 UTC by cw1997

remove non-existent URL

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-07-24 19:42 UTC, jsumners requested changes
Please correct the links instead of removing them.

2023-07-29 20:55 UTC, Uzlopak commented on docs/Reference/Lifecycle.md
> +- the reply serialized if set
```suggestion
- the [reply serialized](./Server.md#set-reply-serializer) if set
```

2023-07-29 20:56 UTC, Uzlopak commented on docs/Reference/Lifecycle.md
> +- or by the serializer compiler when a JSON
```suggestion
- or by the [serializer compiler](./Server.md#set-serializer-compiler) when a JSON
```

2023-07-29 20:59 UTC, Uzlopak commented
Actually the links are correct.

2023-07-29 20:59 UTC, closed without merging