Initial categorization of plugins
fastify/fastify pull request #4938
Opened 2023-07-29 16:25 UTC by JonHPC

Related to https://github.com/fastify/fastify/issues/3618
Sorted Plugins into categories based on https://fastify.github.io/pacchetto/

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-07-29 18:16 UTC, Eomm reviewed
This impact the website build, we need to update it before merging

I would like a tag column instead of a new paragraph. What if a plugin does multiple things?

2023-07-29 20:21 UTC, JonHPC commented
Oh true, I suppose a tag column would make more sense for multiple categories. I'll try to re-work it, thanks!

2023-07-29 21:12 UTC, JonHPC commented
![Screenshot 2023-07-29 at 4 11 01 PM](https://github.com/fastify/fastify/assets/34523493/cdd83239-895e-4ea2-a63a-b0dcb212ff5b)
How about arranging it like this? A table with 3 columns, one for the plugin, one for description, and one for tags.

2023-08-05 16:30 UTC, Eomm reviewed
last feedback: tag lowercase

then LGTM!

2023-08-05 17:13 UTC, jsumners requested changes
Does https://github.com/fastify/fastify/blob/298adbc3cf32b72998736eb503ab61d01c191562/.github/workflows/lint-ecosystem-order.yml still work?

2023-08-06 00:10 UTC, JonHPC commented
> Does https://github.com/fastify/fastify/blob/298adbc3cf32b72998736eb503ab61d01c191562/.github/workflows/lint-ecosystem-order.yml still work?

Hmm, I'm not too sure

2023-08-06 11:13 UTC, metcoder95 commented
> > Does [`298adbc`/.github/workflows/lint-ecosystem-order.yml](https://github.com/fastify/fastify/blob/298adbc3cf32b72998736eb503ab61d01c191562/.github/workflows/lint-ecosystem-order.yml) still work?
> 
> Hmm, I'm not too sure

It is possible to make it work or with the new format it's not? 🙁

2023-08-26 16:36 UTC, Eomm commented
Any update on this?

What is missing:

- [ ] update the lint check https://github.com/fastify/fastify/blob/298adbc3cf32b72998736eb503ab61d01c191562/.github/workflows/lint-ecosystem-order.yml
- [ ] propagate the change to the community plugin
- [ ] for me: update the website before merging this PR

2024-01-29 06:24 UTC, codershiba commented on docs/Guides/Ecosystem.md
> +| [`@fastify/accepts`](https://github.com/fastify/fastify-accepts) |  to have[accepts](https://www.npmjs.com/package/accepts) in your request object. | `http` |
```suggestion
| [`@fastify/accepts`](https://github.com/fastify/fastify-accepts) |  To have [accepts](https://www.npmjs.com/package/accepts) in your request object. | `http` |
```

2024-01-29 06:24 UTC, codershiba commented on docs/Guides/Ecosystem.md
> +| [`@fastify/csrf-protection`](https://github.com/fastify/csrf-protection) | A plugin for adding[CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) protection to Fastify. | `http`   |
```suggestion
| [`@fastify/csrf-protection`](https://github.com/fastify/csrf-protection) | A plugin for adding [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) protection to Fastify. | `http`   |
```

2024-01-29 06:25 UTC, codershiba commented on docs/Guides/Ecosystem.md
> +| [`@fastify/oauth2`](https://github.com/fastify/fastify-oauth2) | Wrap around[`simple-oauth2`](https://github.com/lelylan/simple-oauth2).    | `authentication`   |
```suggestion
| [`@fastify/oauth2`](https://github.com/fastify/fastify-oauth2) | Wrapper around [`simple-oauth2`](https://github.com/lelylan/simple-oauth2).    | `authentication`   |
```

2024-01-29 06:26 UTC, codershiba commented on docs/Guides/Ecosystem.md
> +| [`@fastify/schedule`](https://github.com/fastify/fastify-schedule) | Plugin for scheduling periodic jobs, based on[toad-scheduler](https://github.com/kibertoad/toad-scheduler). | `scheduling`   |
```suggestion
| [`@fastify/schedule`](https://github.com/fastify/fastify-schedule) | Plugin for scheduling periodic jobs, based on [toad-scheduler](https://github.com/kibertoad/toad-scheduler). | `scheduling`   |
```

2024-02-20 17:02 UTC, closed without merging

2024-02-22 10:12 UTC, codershiba commented
Why was this closed

2024-02-22 10:31 UTC, Uzlopak commented
Uff. it was opened 9 months ago :/