added http header types to reply
fastify/fastify pull request #5046
Opened 2023-09-18 18:41 UTC by skwee357

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-09-19 05:25 UTC, Eomm commented on types/reply.d.ts
> +type HttpHeader = 'accept' | 'accept-charset' | 'accept-encoding' | 'accept-language' | 'accept-ranges' | 'access-control-allow-credentials' | 'access-control-allow-headers' | 'access-control-allow-m
Do we have some automation for this list?

> public-key-pins

First time in my life I read it, but:

> in 2017 browsers deprecated and removed HPKP support

https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning

I'm afraid we will get PRs to add whatever HTTP header in the world

2023-09-19 06:01 UTC, mcollina requested changes
Custom http headers are very common. This should also allow any string.

2023-09-19 06:15 UTC, Uzlopak commented
Does this even work????????

type name = 'matteo' | 'eomm' | string

Is afaik because of type widening the same as 
type name = string 

So i doubt that this has any benefit.

2023-09-19 06:16 UTC, Uzlopak requested changes
Blocking because type widening makes this pointless.

2023-09-19 13:05 UTC, mcollina commented
> Blocking because type widening makes this pointless.

This is incorrect. It improves autocompletion.

2023-09-19 13:34 UTC, Uzlopak commented
@mcollina 

Please check yourself

https://www.typescriptlang.org/play?#code/C4TwDgpgBAdghgWwgZygXigcgXYwID2mUAPloQgsWcsAE4CWMA5gLABQHAxgTLVBAAeiMABsIALliIU6LJg5A

no autocompletion.

2023-09-19 17:16 UTC, Eomm commented
For reference:

<img width="685" alt="image" src="https://github.com/fastify/fastify/assets/11404065/9ac009f1-5869-4631-90cc-dd1ad09a885c">

2023-09-19 17:28 UTC, skwee357 commented
A lot of comments, I'll try to address them all:

* I took the list of headers from Rust ```http``` package (as I was porting some Rust code to Node) → https://github.com/hyperium/http/blob/master/src/header/name.rs
* My PR does allow for arbitrary header name, as it allows ```string```
* The motivation behind my PR, is to improve auto-complete and avoid stupid mistakes like ```contest-location``` instead of ```content-location```. I understand it's not 100% bulletproof, but fastify does provide types for request headers → https://github.com/fastify/fastify/blob/main/types/request.d.ts#L59

I'm open for suggestions on how to improve it, but I think typing is necessary.

2023-09-19 18:53 UTC, Uzlopak commented
I take vscode (which uses monaco like typescript playground) as reference. And in vscode this change has no effect.

2023-09-19 18:54 UTC, sergburn commented
Fastify's header name constants come from [`@types/node`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e532df3be90a6f1399387c9e6e93c7da276d55e8/types/node/http.d.ts#L49C75-L49C75), so maybe this is the way they should be defined properly, because as Eomm shows, code completion doesn't work this way.
Code completion would look like this:

<img width="805" alt="image" src="https://github.com/fastify/fastify/assets/1159466/555a95bf-7b3b-48de-81cd-f1da7bb6899b">


However. Node types do not define response header names, maybe for a reason...

2023-09-19 18:57 UTC, skwee357 commented
@sergburn thanks. I agree that it's better to take the header names from ```@types/node```. I wonder why they don't define reply headers, though.

2023-09-19 19:22 UTC, skwee357 commented
Started a discussion in ```@types/node```. Let's see what they will answer and proceed based on their response https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/66753

2023-09-26 08:02 UTC, DemonHa commented
if we do something like this:
```ts
type headers = 'mateo' | 'eonm' | (string & {});
```
it will give us the autocompletion but also we can define general strings
<img width="669" alt="image" src="https://github.com/fastify/fastify/assets/91160178/5ab74cb4-40cb-4431-8d57-28eafafba219">

@Semigradsky @Eomm @mcollina

2023-09-26 11:17 UTC, mcollina commented
`type headers = 'mateo' | 'eonm' | (string & {});` is supported syntax and it works.

Good job.

@skwee357 could you update the PR?

2023-09-26 13:40 UTC, Uzlopak commented
Nice trick. Is there an explaination?

2023-09-26 13:51 UTC, mcollina commented
https://x.com/matteocollina/status/1706595817409093698?s=20

2023-09-26 14:07 UTC, climba03003 commented
Reading through the threads, it may suffer from another issue.
https://github.com/microsoft/TypeScript/issues/29729#issuecomment-554927299

There will be problems on object index.

2023-09-26 20:12 UTC, metcoder95 commented
> if we do something like this:
> 
> ```ts
> type headers = 'mateo' | 'eonm' | (string & {});
> ```
> 
> it will give us the autocompletion but also we can define general strings <img alt="image" width="669" src="https://user-images.githubusercontent.com/91160178/270581384-5ab74cb4-40cb-4431-8d57-28eafafba219.png">


This past week has been full of new learnings. First `split` with the extra arg, and now this 😅 🪄

2023-09-26 20:42 UTC, Uzlopak commented
I patched it now according to @DemonHa suggestion.

Now the question is, is it safe to merge @climba03003 or do you recommend a hard no?

2023-09-26 21:38 UTC, DemonHa commented
> Nice trick. Is there an explaination?

@Uzlopak 
I don't know a clear explanation on this. Might be interesting to look at [this](https://tsplay.dev/mMjZZW). If you hover on type X looks something like this: 

```ts
{
    [x: string & {}]: number;
    alert: number;
    tree: number;
    treegrid: number;
    treeitem: number;
}
```

while if you hover over Y:
```ts
{
    [x: string]: number;
}
```

Somehow it prevent the union to be squashed

[Stackoverflow](https://stackoverflow.com/questions/69793164/typescript-weird-type-intersection-of-string)

2023-09-26 21:54 UTC, DemonHa commented
> Nice trick. Is there an explaination?

@Uzlopak 
There is a great explanation [here](https://stackoverflow.com/questions/75262513/what-is-the-purpose-of-string)

2023-09-26 22:50 UTC, skwee357 commented
> `type headers = 'mateo' | 'eonm' | (string & {});` is supported syntax and it works.
> 
> Good job.
> 
> @skwee357 could you update the PR?

I'm working on adding the types to `@types/node` instead, see here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66783

Once it will be merged, I'll update this PR to use the types from that package, rather that having fastify maintain its own types

2023-12-07 23:59 UTC, Uzlopak commented
@DemonHa 
@skwee357 
@mcollina 
@Eomm 
@metcoder95 
@Semigradsky 
@climba03003 

PTAL

2023-12-08 03:50 UTC, climba03003 commented on types/utils.d.ts
> +export type HttpHeader = keyof OmitIndexSignature<http.OutgoingHttpHeaders> | (string & {}); // eslint-disable-line @typescript-eslint/ban-types
Please add a comment to warn for the usage on return value.
This hack is perfectly fine for `input` value but not for `return` value.
https://github.com/microsoft/TypeScript/issues/29729#issuecomment-554927299

2023-12-08 09:30 UTC, mcollina approved these changes
lgtm

2023-12-08 10:26 UTC, Uzlopak commented
I followed the link provided by @climba03003 and saw that we can do [Record<never, never>](https://github.com/microsoft/TypeScript/issues/29729#issuecomment-1548233969) instead of `{}`. So to avoid that unnessary eslint ignore, i used that.

2023-12-08 17:42 UTC, climba03003 approved these changes

2023-12-08 18:22 UTC, merged