fix(#5049): Remove duplicated calls to onReady
fastify/fastify pull request #5051
Opened 2023-09-20 08:13 UTC by metcoder95

This PR closes #5049

It fixes the double run of `onReady` hooks when calling `Fastify#ready` more than once.
It introduces two new states `booting` (used to indicate `onReady` hooks are running) and `ready` (used to indicate `onReady` hooks have finished running).

> These additions can be subject to change, but I think they are a good starting point.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-09-20 08:35 UTC, mcollina requested changes
I think this implementation is incorrect. While the second call to `ready()` would not execute the hooks, it will resolve _before_ the first one.

2023-09-20 08:51 UTC, Uzlopak commented
Something like this has to be utilized.
https://github.com/fastify/avvio/blob/master/lib/create-promise.js

2023-09-20 09:03 UTC, metcoder95 commented
Yeah, got you. I believe I rushed the implementation a little but wanted to keep a starting point as it was a little bit more complex than I expected.

My initial thought was to keep the promise somewhere, so the same promise could be returned and have deterministic results.

2023-09-20 09:10 UTC, metcoder95 commented
For callbacks, things get more complex, maybe if the app is already booting we keep a record of them and call it sequentially?

The simplest way is just to throw an `error` that the app is already starting (or even a silent warning). Thoughts?

2023-09-20 09:15 UTC, Uzlopak commented
no, with that create promise from avvio you can handle all cases properly.

2023-09-20 09:16 UTC, mcollina commented
Oh I know this is was a tricky problem, that's why I opened a bug instead of sending a quick PR! It's also quite an edge case.

> For callbacks, things get more complex, maybe if the app is already booting we keep a record of them and call them sequentially?

This sounds very tricky. Maybe using an `EventEmitter` somewhere that spins events at the change of states? So if it's booting, you can wait for the "ready" event instead.

> The simplest way is just to throw an error that the app is already starting (or even a silent warning). Thoughts?

This is worse than our current bug :(.

2023-09-20 18:42 UTC, metcoder95 commented
>no, with that create promise from avvio you can handle all cases properly.

Can you elaborate @Uzlopak maybe I'm not getting your suggestion right 🤔 

>Oh I know this is was a tricky problem, that's why I opened a bug instead of sending a quick PR! It's also quite an edge case.

Haha, I realized until I opened the PR 😅 


>Maybe using an EventEmitter somewhere that spins events at the change of states? So if it's booting, you can wait for the "ready" event instead.

Hmm, that sounds interesting. We can keep it tight to the instance and just subscribe new calls to it. I have a rough idea of a similar thing but with the Promise itself; I'll give it a shot to ;)


>This is worse than our current bug :(.

Yeah, don't like it either but it was also an option 😅

2023-09-20 20:18 UTC, Uzlopak commented
I had something like this in mind. It does not work. Maybe it is a dead end. Idk.

```js

  function ready (cb) {
    if (!fastify[kReadyPromise]) {
      fastify[kReadyPromise] = {
        resolve: null,
        reject: null,
        promise: null,
        state: null,
        error: null
      }

      fastify[kReadyPromise].promise = new Promise((resolve, reject) => {
        fastify[kReadyPromise].resolve = (instance) => { fastify[kReadyPromise].state = 1; resolve(instance) }
        fastify[kReadyPromise].reject = (err) => { fastify[kReadyPromise].state = -1; fastify[kReadyPromise].error = err; reject(err) }
      })
      fastify[kReadyPromise].state = 0
    }

    if (fastify[kReadyPromise].state !== 0) {
      if (!cb) {
        return fastify[kReadyPromise].promise
      } else {
        if (fastify[kReadyPromise].state === 1) {
          cb(undefined, fastify)
        } else {
          cb(fastify[kReadyPromise].error)
        }
      }
    }

    // run the hooks after returning the promise
    process.nextTick(runHooks)

    function runHooks () {
      // start loading
      fastify[kAvvioBoot]((err, done) => {
        if (err || fastify[kState].started) {
          manageErr(err)
        } else {
          fastify[kState].booting = true
          hookRunnerApplication('onReady', fastify[kAvvioBoot], fastify, manageErr)
        }
        done()
      })
    }

    function manageErr (err) {
      // If the error comes out of Avvio's Error codes
      // We create a make and preserve the previous error
      // as cause
      err = err != null && AVVIO_ERRORS_MAP[err.code] != null
        ? appendStackTrace(err, new AVVIO_ERRORS_MAP[err.code](err.message))
        : err

      if (err) {
        fastify[kReadyPromise].reject(err)
      } else {
        fastify[kReadyPromise].resolve(fastify)
      }

      if (cb) {
        if (err) {
          cb(err)
        } else {
          cb(undefined, fastify)
        }
      } else {
        return fastify[kReadyPromise].promise
      }
    }
  }
```

2023-09-21 07:54 UTC, metcoder95 commented
Ah ok okay, I see; it is similar to what I was trying to test out. You gave me an idea though, I'll set back the PR into `draft` and re-work the approach 👍

2023-11-12 16:38 UTC, metcoder95 commented
I've refactored it trying to attempt to chain incoming promises down to the first one ever created when initially calling `ready`. That solves mixed implementations from `callbacks` and `promises`, as well as each one independently, but it does not avoids the call to the avvio hook loader. 

We can go in this direction if we think that not avoiding the avvio loader twice is a problem.

2023-11-13 07:57 UTC, Eomm commented on fastify.js
> +      const promise = new Promise(function (resolve, reject) {
```suggestion
      this[kState].readyPromise = new Promise(function (resolve, reject) {
```

2023-11-13 07:57 UTC, Eomm commented on fastify.js
> +      return promise
```suggestion
      return this[kState].readyPromise
```

2023-11-13 07:57 UTC, Eomm commented on test/fastify-instance.test.js
> +test('ready should resolve in order when called multiply times (promises only)', async (t) => {
Could we add the error case too?

2023-11-19 12:35 UTC, metcoder95 commented
Do we have an issue with `warning`?

2023-11-19 12:36 UTC, metcoder95 commented
Tried to enhance sequence handling of the CB and Promises by creating a Promise upfront and using it as a flow control mechanism. Further CB's are attached to the callbacks seeking for ordering.

2023-11-19 12:40 UTC, Eomm commented
> Do we have an issue with `warning`?

We released a fix this morning of the process-warning module. Does it brake the test?
I'm with the mobile 📱 and can't check it right now

2023-11-19 12:43 UTC, metcoder95 commented
It seems so, I rebased with `main` and tests are failing due to:
`warming.emitted.<set | delete | ..>` are not a function.

https://github.com/fastify/fastify/actions/runs/6920346527/job/18824804630?pr=5051#step:5:2881

2023-12-10 17:33 UTC, Uzlopak approved these changes
RSLGTM

2023-12-12 23:44 UTC, Uzlopak approved these changes
Looks right

So no RSLGTM but a LGTM

2023-12-13 02:30 UTC, Uzlopak commented
@mcollina 
PTAL

2023-12-13 06:46 UTC, mcollina approved these changes
lgtm

2023-12-13 07:02 UTC, merged