mention about multipart support
fastify/fastify pull request #5144
Opened 2023-11-05 00:25 UTC by fawazahmed0

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-11-05 09:18 UTC, metcoder95 requested changes
fastify-multipart does not come out of the box with fastify. It’s a plugin that must be installed.

2023-11-05 14:35 UTC, jsumners reviewed
Thank you for the contribution, but I do not think this adds much value. A statement like "other common content types are supported through the use of `[community plugins](link to ecosystem doc)`" might be helpful, but calling out "multipart" specifically is solving only one use case.

2023-11-06 08:59 UTC, metcoder95 approved these changes

2023-11-06 23:07 UTC, jsumners approved these changes
Looks good to me.

2023-11-06 23:07 UTC, merged