add infomation about the beforehandler in the ref page for hooks
fastify/fastify pull request #5163
Opened 2023-11-18 06:27 UTC by RjManhas

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-11-18 18:30 UTC, Eomm commented on docs/Reference/Hooks.md
> +The `beforeHandler` option allows you to specify a function that is executed before the main route handler.
```suggestion
The `preHandler` hook allows you to specify a function that is executed before routes' handler.
```

2023-11-19 18:31 UTC, Fdawgs requested changes
What @Eomm said.

2023-11-22 18:08 UTC, RjManhas commented
i have fixed the suggestions.

2023-11-23 08:25 UTC, Eomm approved these changes

2023-11-23 08:54 UTC, Uzlopak commented on docs/Reference/Hooks.md
> +The `preHandler` hook allows you to specify a function that is executed before routes' handler.
```suggestion
The `preHandler` hook allows you to specify a function that is executed before
routes' handler.
```

2023-11-23 14:12 UTC, jsumners commented on docs/Reference/Hooks.md
> +routes' handler.
```suggestion
a routes's handler.
```

2023-11-24 21:23 UTC, jsumners approved these changes

2023-11-24 23:01 UTC, RjManhas reviewed
did the changes

2023-11-25 10:24 UTC, Fdawgs approved these changes

2023-11-25 10:24 UTC, merged