Gitpodify
fastify/fastify pull request #5168
Opened 2023-11-22 00:58 UTC by ghostdevv

I added an initial gitpod config which will install via npm and add the eslint extension - I'd love to know if there is anything else people usually run when they first jump in to work on a new feature (for example a playground environment) so I can also run that.

I also added an "Open in Gitpod" and "Contribute with Gitpod" button in two places - LMK if there is anywhere I missed

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-11-22 09:37 UTC, mcollina approved these changes
lgtm

2023-11-23 17:20 UTC, Eomm commented on .gitpod.yml
could it be added to .npmignore ?

2023-11-23 17:20 UTC, Eomm commented on README.md
> +[![Contribute with Gitpod](https://img.shields.io/badge/Contribute%20with-Gitpod-908a85?logo=gitpod)](https://gitpod.io/#https://github.com/fastify/fastify)
Gray tells me that something is not working TBH

```suggestion
[![Contribute with Gitpod](https://img.shields.io/badge/Contribute%20with-Gitpod-908a85?logo=gitpod&color=blue)](https://gitpod.io/#https://github.com/fastify/fastify)
```

2023-11-24 18:05 UTC, ghostdevv commented on .gitpod.yml
Done

2023-11-24 18:05 UTC, ghostdevv commented
Updated

2023-11-26 10:30 UTC, metcoder95 approved these changes

2023-11-29 08:51 UTC, Fdawgs requested changes
How useful is this when there is GitHub Codespaces and github.dev available?

2023-11-29 13:08 UTC, pawlean commented
> How useful is this when there is GitHub Codespaces and github.dev available?

Hey @Fdawgs 👋🏼 Pauline from Gitpod here. Great question! We have a full comparison which you can find [here](https://www.gitpod.io/vs/github-codespaces). 😄 Let me know if you have any further questions!

2023-12-02 15:11 UTC, Eomm commented
@Fdawgs Internal discussion: https://github.com/orgs/fastify/discussions/35

2023-12-02 15:12 UTC, Eomm approved these changes

2023-12-03 20:27 UTC, merged

2023-12-05 14:29 UTC, pawlean commented
@Eomm @Fdawgs It's great to see this merged! 

FYI: Fastify qualifies for our Open Source Plan, in partnership with the Linux Foundation [[1](https://www.gitpod.io/blog/linux-foundation-gitpod-partnership)] That is **2500 credits** (or 250 hours) of cloud development environments free of charge!

If you want to make use of this, you can apply directly [here](https://www.gitpod.io/discover/opensource). 🥳  Let me know if you have any questions!