Update parser.js: Add "multipart/form-data" example
fastify/fastify pull request #5205
Opened 2023-12-12 01:31 UTC by David200308

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-12-12 09:12 UTC, mcollina approved these changes
lgtm

2023-12-12 21:10 UTC, Fdawgs requested changes

2023-12-12 21:10 UTC, Fdawgs commented on examples/parser.js
> +const path = require('path');
```suggestion
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
```

2023-12-12 23:02 UTC, Uzlopak requested changes
We should dog food our own @fastify/busboy

2023-12-12 23:07 UTC, Uzlopak commented on examples/parser.js
> +    body += data.toString()
hmm. I guess urlencoded si pure ascii, but if it is multibyte encoded, than this bodyparser could be error prone.

Should be imho:

```js
fastify.addContentTypeParser('application/x-www-form-urlencoded', function (request, payload, done) {
  const body = []
  payload.on('data', function (data) {
    body.push(data)
  })
  payload.on('end', function () {
    try {
      const parsed = querystring.parse(Buffer.concat(body).toString())
      done(null, parsed)
    } catch (e) {
      done(e)
    }
  })
  payload.on('error', done)
})

```

2023-12-14 06:53 UTC, climba03003 requested changes
I would against providing a simple `multipart/form-data` example for everyone.
People always copy and paste the example and it is a critical one that is not safe for copy and paste.

2023-12-31 05:33 UTC, closed without merging