feat(routes): expose findRoute and param validator
fastify/fastify pull request #5230
Opened 2023-12-23 09:49 UTC by sf3ris

### Description
Quick draft of implementation to solve https://github.com/fastify/fastify/issues/5215
In this PR I wanted to expose an abstraction to retrieve a route for doing further checks.
Furthermore, I was doubtful about creating a standalone plugin for a simple check like this but open for any discussion.

#### Checklist

- [*] run `npm run test` and `npm run benchmark`
- [*] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [*] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-12-24 16:30 UTC, metcoder95 commented on lib/route.js
>    }
Overall, I'm +1 on exposing `findRoute` but not in sync with having this validation within core. The scope for the feature seems really specific, that's why the suggestion of having it within a community plugin.

2023-12-24 16:30 UTC, metcoder95 commented on test/findRoute.test.js
Can you add some tests with this being used from a plugin?

2023-12-25 08:48 UTC, mcollina requested changes
We support different kinds of validators. I don't think we should tie with a specific one and having the validations built in. It's likely better to have them in a separate plugin.

2023-12-26 10:43 UTC, sf3ris commented
@mcollina @metcoder95 Makes sense to me, just a bit doubtful about the scope of the plugin.
What do you think about just exposing the `findRoute` as you suggested and leaving the plugin creation\implementation to later discussions?

2023-12-26 11:02 UTC, metcoder95 commented
SGTM 👍

2023-12-26 11:34 UTC, sf3ris commented on test/findRoute.test.js
Added here https://github.com/fastify/fastify/pull/5230/commits/b3ad236cd2c95b905e9e072884ce7f11e3ecf4e6, LMK whether you think is enough or you have other types of tests in mind 🙏

2023-12-26 17:58 UTC, metcoder95 reviewed
Nice! LGTM, small `nit`

2023-12-26 17:58 UTC, metcoder95 commented on fastify.js
> +    findRoute: function _route (options) {
```suggestion
    findRoute: function _findRoute (options) {
```

2023-12-26 18:52 UTC, mcollina commented on types/instance.d.ts
> +  >(opts: Pick<RouteOptions<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider>, 'method' | 'url' | 'constraints'>): FindResult<FindMyWayVersion<RawServer>>;
Could you add a test for this type? We use tsd.

2023-12-27 13:10 UTC, mcollina approved these changes
lgtm

2023-12-27 16:02 UTC, metcoder95 approved these changes

2023-12-27 21:34 UTC, merged