docs(Routes): emphasise the unnecessarity of `async` keyword
fastify/fastify pull request #5242
Opened 2023-12-28 14:29 UTC by tadjik1

`async` keyword is redundant when handler returns promise and no `awaits` are used.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-12-28 19:41 UTC, mcollina requested changes
The point of the example is exactly to show how to use async in this case.

2023-12-28 20:31 UTC, jsumners reviewed
I think this suggestion is more of a "this is how JavaScript works" suggestion than anything specific to Fastify. I don't believe we should be trying to explain everything about the language.

2023-12-28 20:42 UTC, Uzlopak commented
I concur with @jsumners

2023-12-28 22:00 UTC, tadjik1 commented
Yes, I think the example is misleading: it uses callbacks (and setImmediate), being at the same time inside the async/await section of the doc (and async function). So I believe it makes sense to either remove async or replace setImmediate with something else.
In addition: right below this sentence there is a sentence about the async keyword which makes the function return a promise, but the opposite is also true - by returning a promise (return reply) we make the function async for the caller, there is no need to use this keyword.

2023-12-28 23:15 UTC, Uzlopak commented
@tadjik1 
What you wrote makes no sense.

2023-12-29 08:03 UTC, closed without merging

2023-12-29 08:40 UTC, tadjik1 commented
@mcollina @jsumners  maybe this could be an interesting example ([long-polling](https://javascript.info/long-polling) implementation):

```
const clients = new Set();

fastify.get("/subscribe", (request, reply) => {
  clients.add(reply);

  request.raw.on("close", () => clients.delete(reply));

  return reply;
});

fastify.post("/publish", (request) => {
  const message = request.body.message;

  clients.forEach((client) => {
    client.send(message);
  });
  clients.clear();

  return "ok";
});
```