docs: update Ecosystem.md
fastify/fastify pull request #5245
Opened 2023-12-29 20:48 UTC by Bugs5382

* added in fastify-hl7
* updated description of fastify-rabbitmq

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-12-29 20:53 UTC, Bugs5382 commented
Updated my own documentation for the ```fastify-rabbitmq``` plugin and added my newest plugin for  fastify: ```fastify-hl7```

2023-12-29 21:05 UTC, Uzlopak commented on docs/Guides/Ecosystem.md
> +  [node-rabbitmq-client](https://github.com/cody-greene/node-rabbitmq-client))
Isnt the `)` too much?

```suggestion
  [node-rabbitmq-client](https://github.com/cody-greene/node-rabbitmq-client)
```

2023-12-29 22:22 UTC, Bugs5382 commented on docs/Guides/Ecosystem.md
> +  [node-rabbitmq-client](https://github.com/cody-greene/node-rabbitmq-client))
Doh! and Done!

2023-12-29 23:09 UTC, Uzlopak commented
Usually if we add a plugin to our ecosystem, we make a quick review to see if the code is on an acceptable level. When I see your code, then the default branch is basically empty :D. Did you forget to merge your develop branch into the main branch?
The code in the develop branch looks up to standard. Was just confused.

2023-12-30 00:09 UTC, Bugs5382 commented
> Usually if we add a plugin to our ecosystem, we make a quick review to see if the code is on an acceptable level. When I see your code, then the default branch is basically empty :D. Did you forget to merge your develop branch into the main branch? The code in the develop branch looks up to standard. Was just confused.

I usually "sync" your main into my fork. Create a branch. Then do a PR merged from that back to fastify/main. Not sure why you are seeing blank...

2023-12-30 00:10 UTC, Bugs5382 reviewed
LTGTM

2023-12-30 01:22 UTC, Uzlopak approved these changes
LGTM

2023-12-30 01:22 UTC, Uzlopak commented
@Bugs5382 

The src folder in your default branch is empty.

2023-12-30 03:43 UTC, Bugs5382 commented
@Uzlopak  - Ah. Well, I do all my testing and develop in the develop branch (https://github.com/Bugs5382/fastify-hl7/tree/develop). I have published this on the development channel (https://www.npmjs.com/package/fastify-hl7/v/1.0.0-beta.2) overnight so I review it one more time in the morning when my eyes are fresh. :) But it is 100% ready to go, I beleive.

2023-12-30 09:07 UTC, Fdawgs commented
Knew a HL7 plugin would finally turn up.
From reading the quick start it seems similar to Mirth Connect where you're spinning up TCP/IP HL7 listeners?

2023-12-30 09:22 UTC, mcollina requested changes
fastify-hl7 is mostly an empty github repo.

2023-12-30 12:22 UTC, Bugs5382 commented
Merged the code into the main branch. 👍  Released onto the NPM reg.

2023-12-30 12:27 UTC, Bugs5382 commented
> Knew a HL7 plugin would finally turn up. From reading the quick start it seems similar to Mirth Connect where you're spinning up TCP/IP HL7 listeners?

I am. 

It spin up TCP'MLLP inbound connections. It can also "connect" to a remote side. I built with with based off **node-rabbitmq-client** which has a built in auto reconnect for the client at least so that if the server goes off line (i.e. in a kubernetues network or just it restarting from the 'server' going down. Also used another plugin as the base, which hadn't been updated for two years to build HL7 messages as well in strong-typescript fashion. It uses two additional non-fastily plugins I wrote for the underlining technology. :)

2023-12-30 12:28 UTC, Bugs5382 reviewed
It's now in the main branch.

2024-01-01 23:03 UTC, Uzlopak commented
@mcollina PTAL

2024-01-02 09:48 UTC, mcollina approved these changes
lgtm

2024-01-02 09:48 UTC, merged