refactor: deprecate `Reply#getResponseTime()` in favour of `Reply#elapsedTime`
fastify/fastify pull request #5263
Opened 2024-01-11 12:51 UTC by codershiba

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-01-11 14:25 UTC, mcollina requested changes

2024-01-11 14:25 UTC, mcollina commented on lib/reply.js
> +  },
Can you please use this property in `getResponseTime`?

2024-01-11 14:25 UTC, mcollina commented on lib/warnings.js
> +  message: 'You are accessing the deprecated "reply.context" property. Use "request.routeOptions.config" or "request.routeOptions.schema" instead for accessing Route settings. Property "reply.context
why this change?

2024-01-11 14:25 UTC, mcollina commented on lib/reply.js
> +  FSTDEP020()
Can you add a test to check this is correctly emitted. You can modify one of the existing tests for `getResponseTime()`.

2024-01-12 08:14 UTC, codershiba commented
@mcollina Made the requested changes, let me know if I need to do anything else.

2024-01-12 08:55 UTC, metcoder95 commented on test/internals/reply.test.js
> +  })
Maybe refactor this test to compare the `elapsedTime` within `preValidation` and later within `onResponse` to verify the latter is greater than the former?

2024-01-12 09:15 UTC, mcollina requested changes
Can you please update

https://github.com/fastify/fastify/blob/0be27ca0cedf6e74a499f18e73d55aa0ef353b21/lib/reply.js#L816

2024-01-12 10:00 UTC, mcollina approved these changes
lgtm

2024-01-12 10:02 UTC, mcollina commented
seems the tests are failing on CI

2024-01-12 12:07 UTC, codershiba commented
> seems the tests are failing on CI

Fixed

2024-01-12 16:14 UTC, mcollina approved these changes
lgtm

2024-01-13 13:36 UTC, jsumners commented on lib/reply.js
> +    }
```suggestion
    get () {
      if (this[kReplyStartTime] === undefined) {
        return 0
      }
      return (this[kReplyEndTime] || now()) - this[kReplyStartTime]
    }
```

2024-01-13 14:05 UTC, jsumners approved these changes

2024-01-14 14:46 UTC, metcoder95 approved these changes

2024-01-14 19:21 UTC, merged