docs(ecosystem): adds fastify-sqlite-typed to the community plugins list
fastify/fastify pull request #5288
Opened 2024-01-25 14:03 UTC by yoav0gal

Adds ["fastify-sqlite-typed"](https://github.com/yoav0gal/fastify-sqlite-typed) to the community plugins list

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-01-25 14:35 UTC, Fdawgs requested changes

2024-01-25 14:35 UTC, Fdawgs commented on docs/Guides/Ecosystem.md
> +  your application to a sqlite database with full typescript support.
```suggestion
  your application to a SQLite database with full TypeScript support.
```

2024-01-25 15:27 UTC, Fdawgs commented on docs/Guides/Ecosystem.md
> +  your application to a sqlite database with full typescript support.
@yoav0gal TypeScript still needs correcting.

2024-01-25 15:43 UTC, yoav0gal commented on docs/Guides/Ecosystem.md
> +  your application to a sqlite database with full typescript support.
Ops, Thanks!

2024-01-27 15:18 UTC, Fdawgs approved these changes

2024-01-27 22:46 UTC, merged