Update Getting Started guide with ESM usage example
fastify/fastify pull request #5294
Opened 2024-01-26 23:19 UTC by atilagulers

This commit updates the 'Getting Started' guide to include an ESM usage example, specifically demonstrating the export of routes using ESM syntax. A code snippet showing the addition of "type": "module" in a configuration example is also provided to assist users in setting up their projects for ESM.

This addresses the confusion mentioned in issue #5292 regarding ESM configuration in Fastify projects.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-01-27 07:28 UTC, mcollina approved these changes
lgtm

2024-01-27 07:52 UTC, mcollina commented
the markdown is not passing linting

2024-01-27 08:43 UTC, Fdawgs requested changes

2024-01-27 08:43 UTC, Fdawgs commented on docs/Guides/Getting-Started.md
> +>If you're using ECMAScript Modules (ESM) in your project, ensure to
```suggestion
> If you are using ECMAScript Modules (ESM) in your project, be sure to
```

2024-01-27 12:13 UTC, atilagulers commented
@Fdawgs  i've applied changes that you suggested.

2024-01-27 15:17 UTC, Fdawgs approved these changes

2024-01-28 10:24 UTC, metcoder95 approved these changes

2024-01-28 10:24 UTC, merged