chore(ts): Fix links
fastify/fastify pull request #5308
Opened 2024-02-09 11:26 UTC by rozzilla

Fix wrong links/anchors from https://fastify.dev/docs/latest/Reference/TypeScript

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-02-09 11:28 UTC, mcollina approved these changes
lgtm

2024-02-09 11:28 UTC, mcollina commented
Our link checker is now failing

2024-02-09 11:28 UTC, mcollina commented
cc @Fdawgs

2024-02-09 11:29 UTC, rozzilla commented
I don't get why the test fails, but currently one link points to `https://fastify.dev/docs/latest/Reference/TypeScript/Validation-and-Serialization.md/` where the correct path is `https://fastify.dev/docs/latest/Reference/Validation-and-Serialization`

2024-02-09 12:24 UTC, rozzilla commented
@mcollina I know it's sub-optimal, but to fix the CI check I used an absolute URL now 😉 it seems to work

2024-02-09 12:25 UTC, climba03003 requested changes

2024-02-09 12:25 UTC, climba03003 commented on docs/Reference/TypeScript.md
> +Serialization](https://fastify.dev/docs/latest/Reference/Validation-and-Serialization/)
You should not use URL here.

2024-02-09 12:25 UTC, climba03003 commented on docs/Reference/TypeScript.md
> +Providers](https://fastify.dev/docs/latest/Reference/Type-Providers/) page.
You should not use URL here.

2024-02-09 12:27 UTC, climba03003 commented
If the redirection is wrong, please update the website builder. 
Not the markdown, since it is correct when using `./Validation-and-Serialization.md`

2024-02-09 14:21 UTC, rozzilla commented on docs/Reference/TypeScript.md
> +Serialization](https://fastify.dev/docs/latest/Reference/Validation-and-Serialization/)
Done on 24d10bb9 ✅

2024-02-09 14:21 UTC, rozzilla commented on docs/Reference/TypeScript.md
> +Providers](https://fastify.dev/docs/latest/Reference/Type-Providers/) page.
Done on 24d10bb9 ✅

2024-02-09 14:22 UTC, rozzilla commented
> If the redirection is wrong, please update the website builder. Not the markdown, since it is correct when using `./Validation-and-Serialization.md`

@climba03003 PR updated ✅ 

Can you please point me to the website builder logic, so that I can have a look? 🙏🏼

2024-02-09 14:36 UTC, mcollina commented
https://github.com/fastify/website

2024-02-09 15:00 UTC, rozzilla commented
I had a look, but I don't find why only the [TypeScript](https://fastify.dev/docs/latest/Reference/TypeScript/) page this issue occurs 🤔 But I confirm that changing the link to `../Validation-and-Serialization` fixes it also when I locally build the `fastify` website, as you can see from the screenshot
![image](https://github.com/fastify/fastify/assets/3996291/fe5245be-6fd2-403f-b44c-7de4d9fb6371)

2024-02-09 15:06 UTC, climba03003 approved these changes

2024-02-14 07:16 UTC, Uzlopak approved these changes
LGTM

2024-02-14 07:16 UTC, merged

2024-03-19 14:53 UTC, melroy89 commented
> I had a look, but I don't find why only the [TypeScript](https://fastify.dev/docs/latest/Reference/TypeScript/) page has this issue 🤔 Anyway, I confirm that changing the link to `../Validation-and-Serialization` fixes it also when I locally build the `fastify` website, as you can see from the screenshot ![image](https://private-user-images.githubusercontent.com/3996291/303688733-fe5245be-6fd2-403f-b44c-7de4d9fb6371.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NjAyMDUsIm5iZiI6MTcxMDg1OTkwNSwicGF0aCI6Ii8zOTk2MjkxLzMwMzY4ODczMy1mZTUyNDViZS02ZmQyLTQwM2YtYjQ0Yy03ZGU0ZDlmYjYzNzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMTQ1MTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQ1YjFkYzViMjNhYjA1ZGI4MTNiZTA4Njg2OTBkYjM3ZmE2ZmI1ODEwODNhNjg3OTgxNTNlZWI2NjU1YWY5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yMSczj8Ib1gdaX_FWmOuaR9T2ct9N3QjSygL28RT_IU)
> 
> About the "why" it happens, I don't know, never used `docusaurus` before

Yea indeed, only the TypeScript page has this issue. I don't understand why this page create broken links!??

See issue: https://github.com/fastify/website/issues/197

2024-03-19 16:42 UTC, melroy89 commented
> If the redirection is wrong, please update the website builder.

What is wrong with the website build to fix the broken links? And how to update the builder? I couldn't find the root-cause. It's only happening on the TypeScript doc page.