docs: Update errorCodes import and usage
fastify/fastify pull request #5388
Opened 2024-04-05 18:58 UTC by melroy89

#### Checklist

- [x ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-04-05 20:40 UTC, Uzlopak commented on docs/Reference/Errors.md
> +fastify.errorCodes
Why?

2024-04-05 20:41 UTC, Uzlopak requested changes
This PR is not adding any value.

2024-04-06 02:43 UTC, climba03003 requested changes
Actually, you should move the `fastify.errorCodes = errorCodes` to `module.exports.errorCodes = errorCodes`.
Note that it must below `module.exports = fastify`.

2024-04-06 02:44 UTC, climba03003 commented on docs/Reference/Errors.md
> +fastify.errorCodes
Currently, it is not possible to do so.

2024-04-06 06:53 UTC, melroy89 commented
> This PR is not adding any value.

Well actually.. It's showing how ESM errorCodes are currently implemented in fastify. Hence the documentation request.

But we can also improve the code. Either way, the documentation is currently not reflecting how it now works.

2024-04-06 12:29 UTC, melroy89 commented
> Actually, you should move the `fastify.errorCodes = errorCodes` to `module.exports.errorCodes = errorCodes` in `fastify.js`. Note that it must below `module.exports = fastify`.

Like this: https://github.com/fastify/fastify/pull/5390 ?

2024-04-06 12:29 UTC, closed without merging