Fix: [#5409] disable request logging
fastify/fastify pull request #5435
Opened 2024-04-30 07:28 UTC by SamSalvatico

Check for the `disableRequestLogging` to be `false` or `undefined` before logging an error or a 404 during the request

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-05-01 07:51 UTC, metcoder95 reviewed
Nice work!
Tho, I'm over the fence of considering this as a fix as was never stated that this was supported; I'd rather consider it more an enhancement.

Sadly tests are failing.

2024-05-02 07:44 UTC, metcoder95 approved these changes
LGTM 👍

2024-05-02 07:45 UTC, metcoder95 commented
Forgot to mention, can we add some documentation of this within the `disableRequestLogging` option documentation?

2024-05-02 11:12 UTC, mcollina approved these changes
lgtm

2024-05-02 11:24 UTC, Uzlopak approved these changes
hey ho lets go.

2024-05-02 11:24 UTC, Uzlopak commented on docs/Reference/Server.md
> +not existent route is requested
wait... a little typo
```suggestion
non existent route is requested
```

2024-05-02 11:24 UTC, Uzlopak requested changes
small nit

2024-05-02 11:25 UTC, Uzlopak commented on docs/Reference/Server.md
> +not existent route is requested
or 

```suggestion
not existing route is requested
```

2024-05-02 12:29 UTC, Uzlopak approved these changes
lets go

2024-05-02 13:18 UTC, merged