Add tests for error handling
fastify/fastify pull request #5451
Opened 2024-05-06 20:53 UTC by domdomegg

These are failing tests to show that #5445 does not fix #5220

#### Checklist

- [Yes, but see above] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [NA] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-05-06 21:03 UTC, climba03003 requested changes

2024-05-07 17:42 UTC, mcollina commented
@domdomegg would you also add a fix?

2024-05-08 00:22 UTC, domdomegg commented
Hi folk, it's been a while since I've looked at the fastify code, especially since #5222 which this is based off.

I think I was wrong here, and I think #5445 does fix it. Think I've confused myself with misunderstanding some of the errors from the tap test runner 🤦, thank you @climba03003 for flagging this.

Glad this is all finally sorted :)

2024-05-08 02:56 UTC, climba03003 commented
@domdomegg I think this PR still worth merging. Would you consoder re-open and fix the test plan?

2024-05-14 09:06 UTC, gurgunday approved these changes

2024-05-14 09:21 UTC, merged