Fixed a typo in documentation in Database.md
fastify/fastify pull request #5461
Opened 2024-05-12 10:08 UTC by monish001

From: `Each file an migrations folder need`
To: `Each file in migrations folder need`

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-05-12 10:35 UTC, Uzlopak commented
Still doesnt read correct :(

2024-05-12 10:48 UTC, Fdawgs requested changes

2024-05-12 10:48 UTC, Fdawgs commented on docs/Guides/Database.md
> +alter the database schema. Each file in migrations folder need to follow the
```suggestion
alter the database schema. Each file in a migrations folder need to follow the
```

2024-05-13 05:22 UTC, Fdawgs approved these changes

2024-05-13 13:33 UTC, merged