chore: update tap@18
fastify/fastify pull request #5471
Opened 2024-05-17 15:15 UTC by climba03003

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-05-17 15:19 UTC, jsumners commented
Unless things have changed, it's a little bit more involved https://github.com/fastify/fastify/pull/4978/files

2024-05-17 15:27 UTC, climba03003 commented
> Unless things have changed

Have tested locally, it only requires minimal changes.
Is it hard requirement to remove `c8`?

2024-05-17 15:27 UTC, jsumners commented
`tap@18` is using c8 itself.

2024-05-17 15:45 UTC, climba03003 commented
After hanging a bit on removing the external `c8` and using the internal one.
It forced to includes the files that should be ignored in the coverage report.

2024-05-17 19:24 UTC, gurgunday approved these changes

2024-05-18 08:38 UTC, gurgunday commented
Are macos tests flaky?

2024-05-18 09:38 UTC, fox1t approved these changes

2024-05-22 23:31 UTC, gurgunday reviewed
Seems like only macOS fails with a heap limit error

2024-05-26 10:40 UTC, gurgunday commented
Do you know why macOS unit test CI could be failing?

2024-06-03 12:27 UTC, Cangit commented
Test runs out of memory. Its because the test relied on a regression in node v18 that was recently fixed in node v18.9:

`This release fixes a regression introduced in Node.js 18.19.0 where http.server.close() was incorrectly closing idle connections.`

I have updated the test, and also updated to tap19 that was released after this PR was initially opened. 
(Opened as new PR because restrictions) #5495

2024-06-03 23:54 UTC, gurgunday requested changes
Can you update to tap@19 as well?

2024-06-04 07:05 UTC, climba03003 commented on package.json
> +    "coverage:ci-check-coverage": "tap replay",
Replay commands will fail if threshold is not meet
See https://github.com/fastify/fastify/actions/runs/9362073855 for demostration

2024-06-04 11:57 UTC, gurgunday commented on lib/configValidator.js
>  /* istanbul ignore file */
```suggestion
```

2024-06-04 11:58 UTC, gurgunday commented on build/build-error-serializer.js
>  /* istanbul ignore file */
```suggestion
```

2024-06-04 11:58 UTC, gurgunday commented on build/build-validation.js
>  /* istanbul ignore file */
```suggestion
```

2024-06-04 11:58 UTC, gurgunday commented on lib/error-serializer.js
>  /* istanbul ignore file */
```suggestion
```

2024-06-04 11:59 UTC, gurgunday reviewed
`istanbul-ignore`s don't do anything anymore no?

Please make sure to remove them

2024-06-05 02:30 UTC, climba03003 commented on lib/error-serializer.js
> +
Auto generated file is not for review.

2024-06-05 07:04 UTC, gurgunday approved these changes
Looks great, thanks!

2024-06-05 08:41 UTC, merged