docs(reference/typescript): remove type provider from typebox example
fastify/fastify pull request #5576
Opened 2024-07-17 18:37 UTC by jscheffner

I made some small adjustments to the Typescript docs:

* I removed the type provider from the Typebox example. The example uses both a type provider and a generic which makes one of them obsolete. Also to my understanding this part of the docs is supposed to show how to use those libraries without type providers. There's a separate documentation of the type providers.
* I rephrased some sentences, just minor things.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-07-19 06:01 UTC, climba03003 approved these changes
Make sense to remove the `.withTypeProvider`.
It is duplicated.

2024-07-19 06:12 UTC, Fdawgs requested changes

2024-07-19 06:12 UTC, Fdawgs commented on docs/Reference/TypeScript.md
> +Below is how to setup schema validation using the `typebox`, `json-schema-to-typescript` and
```suggestion
Below is how to setup schema validation using the `typebox`, `json-schema-to-typescript`, and
```

Missing Oxford comma.

2024-07-19 10:20 UTC, mcollina requested changes
I don't understand why the type provider has been removed. Can you clarify?

2024-07-19 11:03 UTC, jscheffner commented
> I don't understand why the type provider has been removed. Can you clarify?

Yes I can. There are two mechanisms to get the handler typed:

* You can use the route generic
* You can use a type provider so you don't have to use the generics

But it doesn't help to use both. So in the example there should either be no type provider or no generic. There's a link to the type provider docs just above the examples. There you can find examples using the type providers. Also it says "Below is how to setup schema validation using vanilla typebox and json-schema-to-ts packages." So I think the purpose of the examples was to show how to use the libraries with generics.

2024-07-19 12:13 UTC, mcollina approved these changes
lgtm

2024-07-19 12:24 UTC, Fdawgs approved these changes

2024-07-24 21:52 UTC, gurgunday approved these changes

2024-07-24 23:45 UTC, merged