feat: Codemods for Upgrading to fastify v5
fastify/fastify pull request #5717
Opened 2024-09-27 06:24 UTC by manishjha-04

**🚀 Feature Proposal**

Codemods for Upgrading to fastify v5
Looking forward to add these and help Fastify users have a smooth migration experience.

**Motivation**
The motivation to create codemods is that it would streamline the process for millions of users, and also ensure that the application stays efficient and secure while leveraging the latest advancements in Fastify v5.

**Example**
These codemods would help migrate to fastify v5 real quick as running :

> `npx codemod fastify/5/migrationRecipe`

which would include all the codemods.

2024-10-04 14:05 UTC, mcollina commented
Why is it still a draft? What are you testing these against? have you got a repo with all those breaking changes that I can test against?

2024-10-04 14:30 UTC, arshcodemod commented
@mcollina these have been tested on https://github.com/fastify/fastify/tree/4.x.

Here is the https://github.com/fastify/fastify/pull/5717#issuecomment-2393796298 link to see. Will be marking it for review.

2024-10-04 16:42 UTC, mcollina commented
Most of those seems incorrect, open a PR and I'll comment on them.

2024-10-04 17:23 UTC, manishjha-04 commented
Hi @mcollina, I’ve raised the PR. You might notice double semicolons in several places—this is an issue we're currently addressing with the Codemod CLI. I would love to hear any feedback you have on other areas that may need modifications to improve the Codemod

2025-10-31 09:28 UTC, Eomm commented
We need to push this PR forward

<img width="1526" height="1298" alt="image" src="https://github.com/user-attachments/assets/5e81500b-cde8-4b8e-ad01-c59240cdd618" />

2025-10-31 09:30 UTC, gurgunday approved these changes
Ok, anything missing?

lgtm?

2025-11-01 08:50 UTC, Eomm requested changes

2025-11-01 08:50 UTC, Eomm commented on docs/Guides/Migration-Guide-V5.md
> +> npx codemod@latest fastify/5/route-schema-enhancement
I tried this simple migration locally, but it does not kick in:

<img width="831" height="79" alt="Image" src="https://github.com/user-attachments/assets/8cb42344-f46f-4b01-b14f-b37a15a0182d" />

If I check the source code I can't find that code mode:

- [here it is listed](https://github.com/codemod/fastify-codemods/blob/legacy-codemods/codemods/v5/migration-recipe/.codemodrc.json)
- but [here it is named](https://github.com/codemod/fastify-codemods/tree/legacy-codemods/codemods/v5/querystring-schema-transformer) in a different way: `fastify-3-querystring-schema-transformer`

I think that if we merge this PR, users will complain that it won't work and we will unable to explain why

Could you help us to check these codemodes?

2026-03-09 10:50 UTC, jsumners commented on docs/Guides/Migration-Guide-V5.md
> +
Useless bot. Links are explicitly excluded from the line length rule.

2026-06-17 13:22 UTC, muhammadhasnain3031 commented
Hi! I'm a MERN/Next.js developer and I'd like to work on this issue. Could you please assign it to me?

I'll go through the contributing guidelines and submit a PR. Looking forward to contributing!

2026-06-25 13:56 UTC, kimberly-WY reviewed
Good improvement overall. One edge case: empty string vs null aren't treated the same downstream — might need a normalization step.

2026-08-23 16:48 UTC, ilteoood commented
This has been here for a while. The recipes are not available anymore and we are working to v6 now.
Closing.

2026-08-23 16:48 UTC, closed without merging