test: migrated async-dispose.test.js from tap to node:test
fastify/fastify pull request #5793
Opened 2024-10-28 21:45 UTC by Tony133

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Proposal:

   - migrated `async-dispose.test.js` file from tap to node:test 🔥

2024-10-28 22:27 UTC, gurgunday requested changes
Thanks for the PR!

2024-10-28 22:27 UTC, gurgunday commented on test/async-dispose.test.js
> +  t.assert.equal(fastify.server.listening, true)
```suggestion
  t.assert.strictEqual(fastify.server.listening, true)
```

2024-10-28 22:27 UTC, gurgunday commented on test/async-dispose.test.js
> +  t.assert.equal(fastify.server.listening, false)
```suggestion
  t.assert.strictEqual(fastify.server.listening, false)
```

2024-10-31 04:11 UTC, climba03003 approved these changes

2024-10-31 07:45 UTC, gurgunday approved these changes

2024-10-31 09:47 UTC, merged