docs: fix example for supplying own logger instance
fastify/fastify pull request #5857
Opened 2024-11-22 18:37 UTC by keithito

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included (N/A)
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-11-22 19:14 UTC, jsumners approved these changes

2024-11-22 19:16 UTC, jsumners requested changes
Please correct the linting issue.

2024-11-22 21:09 UTC, keithito commented
> Please correct the linting issue.

Done

2024-11-23 08:59 UTC, metcoder95 approved these changes

2024-11-24 18:57 UTC, Fdawgs approved these changes

2024-11-25 11:52 UTC, jsumners approved these changes

2024-11-25 11:52 UTC, merged