test: migrated find-route.test.js from tap to node:test
fastify/fastify pull request #5867
Opened 2024-11-30 17:06 UTC by Tony133

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Proposal:

 - rename file in `kebab-case`
 - migrated `find-route.test.js` file from `tap` to `node:test` 🔥

2024-12-02 10:55 UTC, climba03003 requested changes

2024-12-02 10:55 UTC, climba03003 commented on test/find-route.test.js
> +  t.assert.deepStrictEqual(route.params.artistId, ':artistId')
```suggestion
  t.assert.strictEqual(route.params.artistId, ':artistId')
```

2024-12-02 10:55 UTC, climba03003 commented on test/find-route.test.js
> +  t.assert.deepStrictEqual(route.params.artistId, ':artistId')
```suggestion
  t.assert.strictEqual(route.params.artistId, ':artistId')
```

2024-12-03 03:50 UTC, climba03003 approved these changes

2024-12-03 16:16 UTC, Eomm approved these changes

2024-12-03 16:17 UTC, merged