test: migrate from tap to node test for close & custom-parser-async
fastify/fastify pull request #5915
Opened 2024-12-30 21:57 UTC by coluzziandrea

These changes are related to issue #5555 

Changed following tests to use `node:test` instead of `tap`:
- `test/close.test.js`
- `test/custom-parser-async.test.js`

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-12-31 03:58 UTC, climba03003 approved these changes

2025-01-02 16:26 UTC, Eomm requested changes

2025-01-02 16:26 UTC, Eomm commented on test/close.test.js
> +      t.assert.ok('close callback')
shouldn't the `testDone` call be here instead?

2025-01-02 16:26 UTC, Eomm commented on test/close.test.js
> +      done()
the `done` is executed before the `catch` callback, we should move it there

2025-01-02 16:26 UTC, Eomm commented on test/custom-parser-async.test.js
> +  fastify.listen({ port: 0 }, async (err) => {
we can't use `async` func as callback

async/await or callback styel

2025-01-04 13:42 UTC, coluzziandrea commented on test/close.test.js
> +      t.assert.ok('close callback')
yes, you're right!

2025-01-04 13:51 UTC, coluzziandrea commented on test/custom-parser-async.test.js
> +  fastify.listen({ port: 0 }, async (err) => {
Roger

2025-01-04 14:13 UTC, coluzziandrea commented
PTAL @Eomm

2025-01-21 20:23 UTC, Eomm approved these changes

2025-01-21 20:23 UTC, merged